// Quests, Gesprächszeilen und Händler für Stufe 20–40 (Thread C, INTEGRATION.md §12.3/§12.5).
// Format wie quests.js. quests.js hängt diese Tabellen an QUESTS, NPC_LINES und VENDORS an.
//
// Geschichte: Ignaroth war nur ein Diener. Die Flammenkrone auf Varkhuls Siegel ist das Zeichen Malgareths,
// des Aschenfürsten, der seit Jahrhunderten auf dem Aschethron jenseits der Glutöde sitzt. Seine Heerführer
// halten jede Region: Khar in der Steppe, Mutter Fäulnis in der Marsch, der Frostwurm in den Zinnen,
// der Glutkoloss vor dem Thron. Am Ende liegt die Flammenkrone in deiner Hand.
import { questXp } from './xp.js';

const Q = (level, weight) => questXp(level, weight);
// Gewichte (Anteil der Stufe, auf der die Quest liegt, × 0,75). Abgestimmt mit test/pacing.mjs (Release-Runde):
// Die Geschichte trägt den Großteil, Malgareth und die Heimkehr bringen fast eine ganze Stufe.
// Kopfgelder und Jagdaufträge füllen die Lücken; Dungeonsuche und Glutprüfungen kommen im Spiel noch dazu.
const W = { travel: 0.07, kill: 0.155, main: 0.18, elite: 0.215, boss: 0.3, side: 0.13, dungeonSide: 0.155, bounty: 0.096, lesson: 0.06, finale: 0.8, epilogue: 1, hunt: 0.06 };

export const QUESTS_40 = {
  // ================================================================ Aschensteppe & Hügelgrab (20–25)
  q_new_horizons: {
    title: 'Neue Horizonte', giver: 'commander_hale', turnInNpc: 'captain_varra', main: true, level: 20, requires: ['q_ignaroth'],
    summary: 'Reise in die Aschensteppe und melde dich bei Hauptfrau Varra.',
    offer: 'Ignaroth ist gefallen, aber die Asche fällt weiter. Meine Späher melden Heere in der Steppe jenseits der Höhen, und sie tragen dasselbe Zeichen, das Maren auf Varkhuls Siegel gefunden hat: eine Krone aus Flammen. Hauptfrau Varra hält dort den letzten Außenposten. Geh zu ihr.',
    progressText: 'Hinter der Rauhwacht führt die Straße hinab in die Aschensteppe.',
    completeText: 'Hale schickt dich? Dann hat er endlich auf meine Briefe gehört. Willkommen am Außenposten. Viel ist nicht übrig, aber es steht noch.',
    objectives: [{ id: 'travel', text: 'Aschensteppe erreicht', count: 1, kind: 'reach', target: ['zone:ashen_steppe', 'steppe_outpost'], zone: 'cinder_peaks' }],
    rewards: { xp: Q(20, W.travel), gold: 120, items: [{ itemId: 'superior_potion', qty: 3 }] },
  },
  q_steppe_raiders: {
    title: 'Staub und Klingen', giver: 'captain_varra', main: true, level: 20, requires: ['q_new_horizons'],
    summary: 'Treibe die Plünderer zurück, die den Außenposten belagern.',
    offer: 'Seit Wochen reiten Plünderer bis an unsere Palisade. Sie tragen Khars Farben, und Khar trägt die Flammenkrone. Erschlag fünfzehn von ihnen, egal ob mit Klinge oder Bogen. Dann wissen sie, dass hier wieder jemand kämpft.',
    progressText: 'Die Plünderer streifen rund um den Außenposten. Fünfzehn müssen fallen.',
    completeText: 'Heute Nacht schläft der Außenposten zum ersten Mal seit Wochen. Hier, nimm das. Du brauchst es dringender als unsere Toten.',
    objectives: [{ id: 'raiders', text: 'Steppenplünderer besiegt', count: 15, kind: 'kill', target: ['steppe_raider', 'raider_archer'], zone: 'ashen_steppe' }],
    rewards: { xp: Q(20, W.kill), gold: 140, gear: [{ ilvl: 21, rarity: 'uncommon', slot: 'weapon' }] },
  },
  q_steppe_banners: {
    title: 'Banner der Krone', giver: 'captain_varra', main: true, level: 21, requires: ['q_steppe_raiders'],
    summary: 'Reiß die drei Kriegsbanner nieder, mit denen Khar die Stämme sammelt.',
    offer: 'Khar hat drei Kriegsbanner in der Steppe aufgestellt. Wo sie wehen, strömen die Stämme zu ihm. Reiß sie nieder, eins nach dem anderen. Ohne Banner ist er nur ein Mann mit einem großen Pferd.',
    progressText: 'Die Banner stehen weit verstreut in der Steppe. Such nach dem Rauch der Wachfeuer.',
    completeText: 'Drei Banner im Staub. Die Stämme werden sich fragen, ob Khar wirklich so stark ist, wie er behauptet.',
    objectives: [{ id: 'banners', text: 'Kriegsbanner niedergerissen', count: 3, kind: 'interact', target: ['war_banner_1', 'war_banner_2', 'war_banner_3'], zone: 'ashen_steppe' }],
    rewards: { xp: Q(21, W.main), gold: 160, gear: [{ ilvl: 22, rarity: 'uncommon', slot: 'chest' }] },
  },
  q_steppe_warcamp: {
    title: 'Das Lager des Fürsten', giver: 'captain_varra', main: true, level: 22, requires: ['q_steppe_banners'],
    summary: 'Dringe zu Khars Kriegslager vor und dünne seine Krieger aus.',
    offer: 'Khar weiß jetzt, dass es dich gibt. Er zieht seine Leute im Kriegslager zusammen. Bevor er zu uns kommt, gehen wir zu ihm. Schlag dich bis zum Lager durch und erschlag fünfzehn seiner Krieger.',
    progressText: 'Das Kriegslager liegt im Norden der Steppe, hinter den Hügeln.',
    completeText: 'Du hast Khars Zelt gesehen? Dann weißt du, wo er schläft. Das ändert alles.',
    objectives: [
      { id: 'camp', text: 'Khars Kriegslager erreicht', count: 1, kind: 'reach', target: ['warlord_camp'], zone: 'ashen_steppe' },
      { id: 'raiders', text: 'Krieger im Lager besiegt', count: 15, kind: 'kill', target: ['steppe_raider', 'raider_archer', 'dust_hyena'], zone: 'ashen_steppe' },
    ],
    rewards: { xp: Q(22, W.main), gold: 180, gear: [{ ilvl: 23, rarity: 'uncommon', slot: 'head' }] },
  },
  q_steppe_warlord: {
    title: 'Khar, der Steppenfürst', giver: 'captain_varra', main: true, level: 23, requires: ['q_steppe_warcamp'],
    summary: 'Besiege Khar in seinem Lager und bring sein Kriegshorn zu Varra.',
    offer: 'Khar reitet nie ohne sein Kriegshorn. Mit ihm ruft er die Stämme, und die Stämme gehorchen. Stell ihn, nimm ihm das Horn ab und bring es mir. Ich will es vor allen Augen zerbrechen.',
    progressText: 'Khar hält sich in der Mitte seines Lagers auf. Er ist kein gewöhnlicher Krieger.',
    completeText: 'Das Horn des Steppenfürsten … Es ist mit einer Flammenkrone verziert. Wer auch immer hinter Khar steht, er sitzt nicht in dieser Steppe.',
    objectives: [
      { id: 'khar', text: 'Khar besiegt', count: 1, kind: 'kill', target: 'steppe_warlord', zone: 'ashen_steppe' },
      { id: 'horn', text: 'Khars Kriegshorn', count: 1, kind: 'collect', target: 'khar_warhorn', from: ['steppe_warlord'], zone: 'ashen_steppe' },
    ],
    rewards: { xp: Q(23, W.elite), gold: 260, gear: [{ ilvl: 24, rarity: 'rare', slot: 'weapon' }] },
  },
  q_barrow_gate: {
    title: 'Das Heulen unter der Erde', giver: 'captain_varra', main: true, level: 24, requires: ['q_steppe_warlord'],
    summary: 'Öffne das Tor zum Heulenden Hügelgrab und stelle dich den Wiedergängern.',
    offer: 'Seit Khar gefallen ist, heult das Hügelgrab jede Nacht. Die Nomaden sagen, der Hügelkönig sei erwacht. Geh zum Grabtor im Osten, steig hinab und erschlag die Toten, die sich dort sammeln.',
    progressText: 'Das Grabtor liegt im Osten der Steppe. Hinter ihm wartet das Heulende Hügelgrab.',
    completeText: 'Du bist zurück und bleich wie die Toten. Aber du bist zurück. Das ist mehr, als die Nomaden von ihren Kundschaftern sagen können.',
    objectives: [
      { id: 'gate', text: 'Grabtor erreicht', count: 1, kind: 'reach', target: ['barrow_gate', 'zone:howling_barrow'], zone: 'ashen_steppe' },
      { id: 'wights', text: 'Wiedergänger im Hügelgrab besiegt', count: 10, kind: 'kill', target: ['barrow_wight', 'grave_hound', 'bone_archer'], zone: 'howling_barrow' },
    ],
    rewards: { xp: Q(24, W.main), gold: 220, gear: [{ ilvl: 25, rarity: 'uncommon', slot: 'hands' }] },
  },
  q_barrow_king: {
    title: 'Der Hügelkönig', giver: 'captain_varra', main: true, level: 25, requires: ['q_barrow_gate'],
    summary: 'Besiege Ulgrim, den Hügelkönig, und bring Varra sein Grabsiegel.',
    offer: 'Ulgrim war vor tausend Jahren König der Steppe. Jemand hat ihn geweckt. Geh in die tiefste Kammer des Hügelgrabs, leg ihn zurück in sein Grab und bring mir sein Siegel. Ich muss wissen, wer ihn gerufen hat.',
    progressText: 'Ulgrim wartet in der Grabkammer am Ende des Hügelgrabs.',
    completeText: 'Wieder die Flammenkrone. Varkhul, Khar, jetzt Ulgrim. Alle tragen dasselbe Zeichen. Die Spur führt nach Norden, durch die Faulmarsch. Dort hält Wächter Thane die Mirefeste.',
    objectives: [
      { id: 'boss', text: 'Ulgrim besiegt', count: 1, kind: 'boss', target: 'barrow_king', zone: 'howling_barrow' },
      { id: 'seal', text: 'Grabsiegel des Hügelkönigs', count: 1, kind: 'collect', target: 'barrow_seal', from: ['barrow_king'], zone: 'howling_barrow' },
    ],
    rewards: { xp: Q(25, W.boss), gold: 420, gear: [{ ilvl: 26, rarity: 'rare', slot: 'chest' }] },
  },
  q_into_the_marsh: {
    title: 'In die Faulmarsch', giver: 'captain_varra', turnInNpc: 'warden_thane', main: true, level: 25, requires: ['q_barrow_king'],
    summary: 'Reise in die Faulmarsch und melde dich bei Wächter Thane in der Mirefeste.',
    offer: 'Thane ist ein sturer Hund, aber er hält die Mirefeste seit zwanzig Jahren. Wenn jemand weiß, was in der Marsch vor sich geht, dann er. Nimm den Weg nach Norden, am Marschrand entlang.',
    progressText: 'Folge der Straße nach Norden bis zum Marschrand und weiter zur Mirefeste.',
    completeText: 'Varra schickt mir einen Helden? Hier sterben Helden schneller als Mücken. Aber gut. Komm rein, bevor der Nebel dich frisst.',
    objectives: [{ id: 'travel', text: 'Mirefeste erreicht', count: 1, kind: 'reach', target: ['zone:blighted_marsh', 'mirefort'], zone: 'ashen_steppe' }],
    rewards: { xp: Q(25, W.travel), gold: 150, items: [{ itemId: 'superior_potion', qty: 3 }] },
  },

  // --- Orla (Reiten)
  q_first_ride: {
    title: 'Reitunterricht', giver: 'stablemaster_orla', level: 20, minLevel: 20, requires: ['q_ignaroth'],
    summary: 'Bring Orla Hyänenfelle für einen Sattel und lerne das Reiten.',
    offer: 'Du willst reiten? Dann lern es richtig. Erst brauchst du einen Sattel, und ein guter Sattel braucht Hyänenfell. Bring mir sechs Felle. Dann zeige ich dir, wie man aufsitzt, ohne sich den Hals zu brechen.',
    progressText: 'Die Staubhyänen jagen in Rudeln in der offenen Steppe.',
    completeText: 'Gute Felle. Und jetzt hoch mit dir … Fersen runter, Rücken gerade. Siehst du, du kannst reiten. Ein Tier bekommst du von mir aber nicht geschenkt. Meine Pferde kosten, und wilde Tiere musst du dir selbst verdienen.',
    objectives: [{ id: 'hides', text: 'Hyänenfelle gesammelt', count: 6, kind: 'collect', target: 'hyena_hide', from: ['dust_hyena'], zone: 'ashen_steppe' }],
    rewards: { xp: Q(20, W.lesson), gold: 80 },
  },

  // --- Kesh (Nebenquests)
  q_steppe_hyenas: {
    title: 'Lachen in der Nacht', giver: 'nomad_kesh', level: 20, requires: ['q_new_horizons'],
    summary: 'Erlege die Staubhyänen, die Keshs Herde reißen.',
    offer: 'Hörst du das Lachen? Das sind die Hyänen. Sie haben drei meiner Ziegen geholt, und sie lachen dabei. Erlege zwölf von ihnen. Dann lache ich.',
    progressText: 'Die Hyänen jagen im Rudel. Greif nie nur eine an.',
    completeText: 'Es ist still draußen. Endlich still. Nimm das, meine Großmutter hat es genäht.',
    objectives: [{ id: 'hyenas', text: 'Staubhyänen erlegt', count: 12, kind: 'kill', target: 'dust_hyena', zone: 'ashen_steppe' }],
    rewards: { xp: Q(20, W.side), gold: 110, gear: [{ ilvl: 21, rarity: 'uncommon', slot: 'feet' }] },
  },
  q_steppe_feathers: {
    title: 'Federn für die Pfeile', giver: 'nomad_kesh', level: 21, requires: ['q_steppe_hyenas'],
    summary: 'Sammle Geierfedern für die Pfeile der Nomaden.',
    offer: 'Unsere Pfeile fliegen krumm, seit die Plünderer unsere Vorräte verbrannt haben. Die Aschegeier kreisen über jedem Schlachtfeld. Hol mir acht ihrer Federn, dann fliegen unsere Pfeile wieder gerade.',
    progressText: 'Die Aschegeier stoßen von oben herab. Warte, bis sie tief fliegen.',
    completeText: 'Gute Federn, grau vom Wind. Meine Söhne werden heute Nacht Pfeile schnitzen.',
    objectives: [{ id: 'feathers', text: 'Geierfedern gesammelt', count: 8, kind: 'collect', target: 'vulture_feather', from: ['ash_vulture'], zone: 'ashen_steppe' }],
    rewards: { xp: Q(21, W.side), gold: 120, items: [{ itemId: 'steppe_jerky', qty: 5 }] },
  },
  q_steppe_arrowheads: {
    title: 'Gestohlene Spitzen', giver: 'nomad_kesh', level: 22, requires: ['q_steppe_feathers'],
    summary: 'Hol die Pfeilspitzen zurück, die die Plünderer den Nomaden gestohlen haben.',
    offer: 'Federn haben wir jetzt, aber keine Spitzen. Die Bogenschützen der Plünderer haben unsere Schmiede ausgeräumt. Nimm ihnen acht Spitzen ab. Sie schulden sie uns.',
    progressText: 'Die Plündererschützen halten sich am Rand der Kämpfe.',
    completeText: 'Das sind unsere. Ich erkenne die Kerben. Die Plünderer werden sie gleich wiedersehen, nur von der anderen Seite.',
    objectives: [{ id: 'heads', text: 'Plündererspitzen gesammelt', count: 8, kind: 'collect', target: 'raider_arrowhead', from: ['raider_archer'], zone: 'ashen_steppe' }],
    rewards: { xp: Q(22, W.side), gold: 130, gear: [{ ilvl: 23, rarity: 'uncommon', slot: 'ring' }] },
  },
  q_barrow_bones: {
    title: 'Knochen der Ahnen', giver: 'nomad_kesh', level: 24, requires: ['q_steppe_arrowheads', 'q_steppe_warlord'],
    summary: 'Bring die Knochen der Nomaden-Ahnen aus dem Hügelgrab zurück.',
    offer: 'Im Hügelgrab liegen nicht nur Könige. Auch meine Ahnen. Jetzt laufen ihre Knochen herum und kämpfen für jemand anderen. Bring mir sechs zurück, damit wir sie richtig begraben können.',
    progressText: 'Die Wiedergänger und Knochenschützen im Hügelgrab tragen die Knochen der Ahnen.',
    completeText: 'Sie sind kalt. Kälter als Stein. Heute Nacht singen wir für sie. Danke, Fremder.',
    objectives: [{ id: 'bones', text: 'Hügelgrabknochen geborgen', count: 6, kind: 'collect', target: 'barrow_bone', from: ['barrow_wight', 'bone_archer'], zone: 'howling_barrow' }],
    rewards: { xp: Q(24, W.dungeonSide), gold: 160, gear: [{ ilvl: 25, rarity: 'uncommon', slot: 'amulet' }] },
  },
  q_barrow_callers: {
    title: 'Die Rufer der Toten', giver: 'nomad_kesh', level: 25, requires: ['q_barrow_bones'],
    summary: 'Bring die Totenrufer im Hügelgrab zum Schweigen.',
    offer: 'Die Knochen stehen wieder auf, weil jemand sie ruft. Die Nomaden nennen sie Totenrufer, Wiedergänger mit Stimmen wie Wind in Höhlen. Zwei von ihnen sind im Grab. Bring sie zum Schweigen.',
    progressText: 'Die Totenrufer beschwören ständig neue Knochen. Greif sie zuerst an.',
    completeText: 'Es ist still im Grab. Zum ersten Mal seit Monden. Mein Stamm steht in deiner Schuld.',
    objectives: [{ id: 'callers', text: 'Totenrufer besiegt', count: 2, kind: 'kill', target: 'wight_caller', zone: 'howling_barrow' }],
    rewards: { xp: Q(25, W.dungeonSide), gold: 180, gear: [{ ilvl: 25, rarity: 'rare', slot: 'feet' }] },
  },

  // ================================================================ Faulmarsch & Sporenschlund (25–31)
  q_marsh_lurkers: {
    title: 'Was im Wasser lauert', giver: 'warden_thane', main: true, level: 25, requires: ['q_into_the_marsh'],
    summary: 'Säubere die Wege rund um die Mirefeste von Moorlauerern.',
    offer: 'Die Moorlauerer ziehen meine Späher ins Wasser, einen nach dem anderen. Wenn du hier nützlich sein willst, erschlag fünfzehn von ihnen. Dann reden wir über alles andere.',
    progressText: 'Die Moorlauerer warten im flachen Wasser neben den Stegen.',
    completeText: 'Fünfzehn. Nicht schlecht für jemanden aus dem Süden. Vielleicht bleibst du doch länger als eine Woche am Leben.',
    objectives: [{ id: 'lurkers', text: 'Moorlauerer erschlagen', count: 15, kind: 'kill', target: 'bog_lurker', zone: 'blighted_marsh' }],
    rewards: { xp: Q(25, W.kill), gold: 190, gear: [{ ilvl: 26, rarity: 'uncommon', slot: 'weapon' }] },
  },
  q_marsh_totems: {
    title: 'Totems der Fäulnis', giver: 'warden_thane', main: true, level: 26, requires: ['q_marsh_lurkers'],
    summary: 'Verbrenne die drei Faultotems, die den Nebel über der Marsch halten.',
    offer: 'Der Nebel ist nicht natürlich. Die Faulpriester haben drei Totems aufgestellt, die ihn nähren. Verbrenn sie. Wenn der Nebel lichter wird, sehen wir endlich, womit wir es zu tun haben.',
    progressText: 'Die Totems stehen tief im Nebel. Folge dem Gestank.',
    completeText: 'Der Nebel reißt auf. Und da hinten, siehst du das? Pilze, groß wie Türme. Irgendetwas wächst dort, und es wächst schnell.',
    objectives: [{ id: 'totems', text: 'Faultotems verbrannt', count: 3, kind: 'interact', target: ['rot_totem_1', 'rot_totem_2', 'rot_totem_3'], zone: 'blighted_marsh' }],
    rewards: { xp: Q(26, W.main), gold: 210, gear: [{ ilvl: 27, rarity: 'uncommon', slot: 'chest' }] },
  },
  q_marsh_shamans: {
    title: 'Die Faulpriester', giver: 'warden_thane', main: true, level: 27, requires: ['q_marsh_totems'],
    summary: 'Besiege die Faulpriester und bring ihre Götzen zu Thane.',
    offer: 'Die Faulpriester beten zu etwas, das im Sporenschlund sitzt. Sie nennen es Mutter. Erschlag zehn von ihnen und bring mir fünf ihrer Götzen. Ich will wissen, wen sie anbeten.',
    progressText: 'Die Faulpriester wirken ihre Zauber aus sicherer Entfernung. Geh nah heran.',
    completeText: 'Mutter Fäulnis. So nennen sie es. Und auf jedem Götzen dieselbe Krone aus Flammen. Varra hatte recht, das ist größer als die Marsch.',
    objectives: [
      { id: 'shamans', text: 'Faulpriester besiegt', count: 10, kind: 'kill', target: 'rot_shaman', zone: 'blighted_marsh' },
      { id: 'idols', text: 'Faulgötzen erbeutet', count: 5, kind: 'collect', target: 'rot_idol', from: ['rot_shaman'], zone: 'blighted_marsh' },
    ],
    rewards: { xp: Q(27, W.main), gold: 230, gear: [{ ilvl: 28, rarity: 'uncommon', slot: 'head' }] },
  },
  q_sunken_village: {
    title: 'Das versunkene Dorf', giver: 'warden_thane', main: true, level: 28, requires: ['q_marsh_shamans'],
    summary: 'Durchsuche das versunkene Dorf und vernichte die Seuchenkröten und Egel.',
    offer: 'Weiter im Norden lag ein Dorf. Dann kam die Fäulnis und das Dorf sank. Die Kröten dort speien Gift, die Egel saugen alles aus, was noch lebt. Geh hin und räum auf. Fünfzehn von dem Viehzeug.',
    progressText: 'Das versunkene Dorf liegt nördlich der Mirefeste. Halte Abstand zu den Giftwolken.',
    completeText: 'Du hast das Dorf gesehen. Ich war dort, als es noch Kinder hatte. Danke, dass du es ihnen zurückgegeben hast, auch wenn niemand mehr dort wohnt.',
    objectives: [
      { id: 'village', text: 'Versunkenes Dorf erreicht', count: 1, kind: 'reach', target: ['sunken_village'], zone: 'blighted_marsh' },
      { id: 'pests', text: 'Seuchenkröten und Sumpfegel vernichtet', count: 15, kind: 'kill', target: ['plague_toad', 'swamp_leech'], zone: 'blighted_marsh' },
    ],
    rewards: { xp: Q(28, W.main), gold: 250, gear: [{ ilvl: 29, rarity: 'uncommon', slot: 'feet' }] },
  },
  q_bog_horror: {
    title: 'Das Moorgrauen', giver: 'warden_thane', main: true, level: 29, requires: ['q_sunken_village'],
    summary: 'Stelle das Moorgrauen und bring Thane sein Herz.',
    offer: 'Etwas Großes lebt in den tiefen Tümpeln. Die Leute nennen es das Moorgrauen. Es hat mehr meiner Wächter gefressen als alle Lauerer zusammen. Töte es und bring mir sein Herz. Ich will zusehen, wie es brennt.',
    progressText: 'Das Moorgrauen haust in den tiefsten Tümpeln der Marsch.',
    completeText: 'Es schlägt noch, das verdammte Ding. Ins Feuer damit. So. Jetzt kann ich wieder schlafen.',
    objectives: [
      { id: 'horror', text: 'Moorgrauen besiegt', count: 1, kind: 'kill', target: 'bog_horror', zone: 'blighted_marsh' },
      { id: 'heart', text: 'Herz des Moorgrauens', count: 1, kind: 'collect', target: 'horror_heart', from: ['bog_horror'], zone: 'blighted_marsh' },
    ],
    rewards: { xp: Q(29, W.elite), gold: 330, gear: [{ ilvl: 30, rarity: 'rare', slot: 'weapon' }] },
  },
  q_spore_gate: {
    title: 'Der Sporenschlund', giver: 'warden_thane', main: true, level: 30, requires: ['q_bog_horror'],
    summary: 'Dringe in den Sporenschlund ein und vernichte die Pilzbrut.',
    offer: 'Die Pilztürme wachsen aus einem Schlund im Norden. Dort sitzt Mutter Fäulnis, und dort wachsen ihre Kinder. Geh hinab und vernichte zwölf von ihrer Brut, bevor sie die ganze Marsch überwuchert.',
    progressText: 'Der Eingang zum Sporenschlund liegt am Sporentor im Norden der Marsch.',
    completeText: 'Du riechst nach Pilzen. Wasch dich, bevor du das Lager betrittst. Und dann erzähl mir, was du da unten gesehen hast.',
    objectives: [
      { id: 'gate', text: 'Sporentor erreicht', count: 1, kind: 'reach', target: ['spore_gate', 'zone:spore_hollow'], zone: 'blighted_marsh' },
      { id: 'spores', text: 'Pilzbrut vernichtet', count: 12, kind: 'kill', target: ['sporeling', 'fungal_brute', 'spore_caster'], zone: 'spore_hollow' },
    ],
    rewards: { xp: Q(30, W.main), gold: 270, gear: [{ ilvl: 31, rarity: 'uncommon', slot: 'hands' }] },
  },
  q_rot_mother: {
    title: 'Mutter Fäulnis', giver: 'warden_thane', main: true, level: 31, requires: ['q_spore_gate'],
    summary: 'Vernichte Mutter Fäulnis im Herzen des Sporenschlunds.',
    offer: 'Es gibt nur einen Weg, die Marsch zu retten. Mutter Fäulnis muss sterben. Ihr Nest liegt im tiefsten Teil des Schlunds. Geh hinab und komm nicht zurück, bevor sie tot ist.',
    progressText: 'Mutter Fäulnis wartet in ihrem Nest am Grund des Sporenschlunds.',
    completeText: 'Der Nebel lichtet sich. Zum ersten Mal seit Jahren sehe ich die Berge im Norden. Die Frostzinnen. Von dort kommt die Kälte, und von dort kam der Befehl an die Mutter, das sagen die Götzen. Jarl Eskil hält Frosthold.',
    objectives: [{ id: 'boss', text: 'Mutter Fäulnis vernichtet', count: 1, kind: 'boss', target: 'rot_mother', zone: 'spore_hollow' }],
    rewards: { xp: Q(31, W.boss), gold: 560, gear: [{ ilvl: 32, rarity: 'rare', slot: 'chest' }] },
  },
  q_frost_pass: {
    title: 'Der Frostpass', giver: 'warden_thane', turnInNpc: 'jarl_eskil', main: true, level: 31, requires: ['q_rot_mother'],
    summary: 'Überquere den Frostpass und melde dich bei Jarl Eskil in Frosthold.',
    offer: 'Der Pass nach Norden ist offen, jetzt wo der Nebel weg ist. Jarl Eskil herrscht in Frosthold. Er hasst Fremde, aber er hasst die Flammenkrone mehr. Sag ihm, Thane schickt dich.',
    progressText: 'Der Frostpass beginnt am Nordrand der Marsch.',
    completeText: 'Thane lebt noch? Dieser alte Moorhund. Gut. Setz dich ans Feuer, Fremder. Hier oben erfriert man schneller, als man stirbt.',
    objectives: [{ id: 'travel', text: 'Frosthold erreicht', count: 1, kind: 'reach', target: ['zone:frostspire', 'frosthold'], zone: 'blighted_marsh' }],
    rewards: { xp: Q(31, W.travel), gold: 180, items: [{ itemId: 'supreme_potion', qty: 3 }] },
  },

  // --- Brisa (Nebenquests)
  q_marsh_leeches: {
    title: 'Egelschleim', giver: 'alchemist_brisa', level: 25, requires: ['q_into_the_marsh'],
    summary: 'Sammle Egelschleim für Brisas Gegengift.',
    offer: 'Die Hälfte der Wächter liegt mit Sumpffieber im Lager. Mein Gegengift braucht Egelschleim. Viel Egelschleim. Acht Portionen, und bitte nicht in der Hosentasche transportieren.',
    progressText: 'Die Sumpfegel schwärmen im flachen Wasser.',
    completeText: 'Wunderbar eklig. Das reicht für das ganze Lager. Hier, nimm ein paar Tränke. Die sind nicht aus Egeln. Glaube ich.',
    objectives: [{ id: 'ichor', text: 'Egelschleim gesammelt', count: 8, kind: 'collect', target: 'leech_ichor', from: ['swamp_leech'], zone: 'blighted_marsh' }],
    rewards: { xp: Q(25, W.side), gold: 150, items: [{ itemId: 'superior_potion', qty: 4 }] },
  },
  q_marsh_toads: {
    title: 'Drüsen und Dämpfe', giver: 'alchemist_brisa', level: 26, requires: ['q_marsh_leeches'],
    summary: 'Hol Brisa die Giftdrüsen der Seuchenkröten.',
    offer: 'Das Gegengift hilft gegen das Fieber. Gegen das Krötengift hilft es nicht. Dafür brauche ich das Gift selbst, frisch aus der Drüse. Sechs Stück. Halt die Luft an, wenn die Kröten sich aufblähen.',
    progressText: 'Die Seuchenkröten sitzen in den Sümpfen nördlich der Feste.',
    completeText: 'Sie pulsieren noch! Perfekt. Mit etwas Glück kann bald niemand mehr an diesen Viechern sterben.',
    objectives: [{ id: 'glands', text: 'Krötendrüsen gesammelt', count: 6, kind: 'collect', target: 'toad_gland', from: ['plague_toad'], zone: 'blighted_marsh' }],
    rewards: { xp: Q(26, W.side), gold: 160, gear: [{ ilvl: 27, rarity: 'uncommon', slot: 'amulet' }] },
  },
  q_lost_caravan: {
    title: 'Die verlorene Karawane', giver: 'alchemist_brisa', level: 27, requires: ['q_marsh_toads'],
    summary: 'Finde Brisas verschollene Karawane und vertreibe die Lauerer, die sie belagern.',
    offer: 'Meine Karawane aus dem Süden ist überfällig. Sie hatte alles dabei, was ich zum Brauen brauche. Such sie. Sie müsste irgendwo am alten Damm stecken. Und wenn Lauerer in der Nähe sind, du weißt, was zu tun ist.',
    progressText: 'Die Karawane steckt irgendwo am alten Damm fest.',
    completeText: 'Die Wagen sind versunken, aber die Kisten sind dicht. Du hast mir den Monat gerettet. Vielleicht das Jahr.',
    objectives: [
      { id: 'caravan', text: 'Verlorene Karawane gefunden', count: 1, kind: 'interact', target: ['lost_caravan'], zone: 'blighted_marsh' },
      { id: 'lurkers', text: 'Lauerer an der Karawane erschlagen', count: 10, kind: 'kill', target: 'bog_lurker', zone: 'blighted_marsh' },
    ],
    rewards: { xp: Q(27, W.side), gold: 200, gear: [{ ilvl: 28, rarity: 'rare', slot: 'hands' }] },
  },
  q_marsh_iron: {
    title: 'Eisen aus dem Moor', giver: 'alchemist_brisa', level: 28, requires: ['q_lost_caravan'],
    summary: 'Bring Brisa Moorraseneisen für neue Kessel.',
    offer: 'Mein Kessel ist durchgerostet. Hier gibt es kein gutes Eisen, außer dem, das die Lauerer vom Grund hochholen. Die fressen das Zeug, glaube ich. Bring mir sechs Brocken.',
    progressText: 'Moorlauerer tragen Moorraseneisen im Magen. Frag nicht.',
    completeText: 'Schwer und rot. Genau richtig. Heute Abend brauen wir in einem Kessel ohne Loch.',
    objectives: [{ id: 'iron', text: 'Moorraseneisen gesammelt', count: 6, kind: 'collect', target: 'bog_iron', from: ['bog_lurker'], zone: 'blighted_marsh' }],
    rewards: { xp: Q(28, W.side), gold: 210, items: [{ itemId: 'greater_mana', qty: 4 }] },
  },
  q_marsh_cure: {
    title: 'Ein Heilmittel aus Sporen', giver: 'alchemist_brisa', level: 30, requires: ['q_marsh_iron', 'q_bog_horror'],
    summary: 'Sammle Sporenkappen im Sporenschlund für Brisas Heilmittel.',
    offer: 'Was krank macht, kann auch heilen, wenn man es richtig braut. Die Pilze im Sporenschlund sind die Quelle der Fäulnis. Bring mir sechs Sporenkappen, und ich mache daraus etwas, das die Marsch heilt.',
    progressText: 'Die Sporlinge und Sporenwirker im Schlund tragen Sporenkappen.',
    completeText: 'Leuchtend, frisch, giftig. Perfekt. Wenn das klappt, singen sie in der Mirefeste Lieder über dich. Schlechte Lieder, aber immerhin.',
    objectives: [{ id: 'caps', text: 'Sporenkappen gesammelt', count: 6, kind: 'collect', target: 'spore_cap', from: ['sporeling', 'spore_caster'], zone: 'spore_hollow' }],
    rewards: { xp: Q(30, W.dungeonSide), gold: 240, gear: [{ ilvl: 31, rarity: 'rare', slot: 'ring' }] },
  },

  // ================================================================ Frostzinnen & Reifhöhlen (31–36)
  q_frost_wolves: {
    title: 'Das Rudel der Zinnen', giver: 'jarl_eskil', main: true, level: 31, requires: ['q_frost_pass'],
    summary: 'Erlege die Frostwölfe, die die Wege nach Frosthold unsicher machen.',
    offer: 'Die Frostwölfe jagen seit dem letzten Mond auf meinen Straßen. Sonst halten sie sich an die Berge. Jemand treibt sie herunter. Erlege fünfzehn, dann glaube ich dir, dass Thane dich nicht umsonst geschickt hat.',
    progressText: 'Die Frostwölfe jagen im Rudel auf den Straßen unterhalb von Frosthold.',
    completeText: 'Fünfzehn Felle. Die Skalden werden davon singen. Kurz. Hier oben singen sie nur kurz, sonst frieren ihnen die Lippen fest.',
    objectives: [{ id: 'wolves', text: 'Frostwölfe erlegt', count: 15, kind: 'kill', target: 'frost_wolf', zone: 'frostspire' }],
    rewards: { xp: Q(31, W.kill), gold: 240, gear: [{ ilvl: 32, rarity: 'uncommon', slot: 'weapon' }] },
  },
  q_frost_beacons: {
    title: 'Die Leuchtfeuer', giver: 'jarl_eskil', main: true, level: 32, requires: ['q_frost_wolves'],
    summary: 'Entzünde die drei Leuchtfeuer der Frostzinnen.',
    offer: 'Früher brannten drei Leuchtfeuer auf den Zinnen. Solange sie brannten, wagte sich kein Troll ins Tal. Die Hexen haben sie gelöscht. Entzünde sie wieder, und die Trolle bleiben, wo sie hingehören.',
    progressText: 'Die Leuchtfeuer stehen auf drei Gipfeln der Frostzinnen.',
    completeText: 'Drei Feuer auf den Zinnen. Mein Vater hätte geweint. Ich weine nicht. Es ist nur der Wind.',
    objectives: [{ id: 'beacons', text: 'Leuchtfeuer entzündet', count: 3, kind: 'interact', target: ['frost_beacon_1', 'frost_beacon_2', 'frost_beacon_3'], zone: 'frostspire' }],
    rewards: { xp: Q(32, W.main), gold: 260, gear: [{ ilvl: 33, rarity: 'uncommon', slot: 'chest' }] },
  },
  q_troll_caves: {
    title: 'Die Trollhöhlen', giver: 'jarl_eskil', main: true, level: 33, requires: ['q_frost_beacons'],
    summary: 'Dringe in die Trollhöhlen vor und erschlage die Eistrolle.',
    offer: 'Die Feuer halten die Trolle vom Tal fern, aber nicht aus ihren Höhlen. Dort sammeln sie sich, dutzende. Geh hinein und erschlag fünfzehn, bevor sie genug sind, um Frosthold zu stürmen.',
    progressText: 'Die Trollhöhlen liegen im Osten der Frostzinnen.',
    completeText: 'Fünfzehn Trolle. Ich habe in meinem Leben drei erschlagen und darauf ein Fass geleert. Für dich rolle ich zwei heraus.',
    objectives: [
      { id: 'caves', text: 'Trollhöhlen erreicht', count: 1, kind: 'reach', target: ['troll_caves'], zone: 'frostspire' },
      { id: 'trolls', text: 'Eistrolle erschlagen', count: 15, kind: 'kill', target: 'ice_troll', zone: 'frostspire' },
    ],
    rewards: { xp: Q(33, W.main), gold: 280, gear: [{ ilvl: 34, rarity: 'uncommon', slot: 'head' }] },
  },
  q_troll_chief: {
    title: 'Gorm Eisfaust', giver: 'jarl_eskil', main: true, level: 34, requires: ['q_troll_caves'],
    summary: 'Besiege Gorm Eisfaust und bring Eskil seinen Hauer.',
    offer: 'Gorm Eisfaust führt die Trolle. Er ist größer als drei Männer und schlauer als die meisten Jarle. Er trägt die Flammenkrone auf der Brust, eingebrannt ins Fell. Bring mir seinen Hauer, damit mein Volk sieht, dass er tot ist.',
    progressText: 'Gorm hält sich in der tiefsten Trollhöhle auf.',
    completeText: 'Das ist Gorms Hauer, keine Frage. Frosthold wird heute Nacht feiern. Aber ich habe seine Brust gesehen, als er fiel. Dieses Brandzeichen … Die Krone ruft von Norden, aus den Reifhöhlen.',
    objectives: [
      { id: 'gorm', text: 'Gorm Eisfaust besiegt', count: 1, kind: 'kill', target: 'ice_troll_chief', zone: 'frostspire' },
      { id: 'tusk', text: 'Gorms Hauer', count: 1, kind: 'collect', target: 'gorm_tusk', from: ['ice_troll_chief'], zone: 'frostspire' },
    ],
    rewards: { xp: Q(34, W.elite), gold: 400, gear: [{ ilvl: 35, rarity: 'rare', slot: 'weapon' }] },
  },
  q_rime_witches: {
    title: 'Die Reifhexen', giver: 'jarl_eskil', main: true, level: 34, requires: ['q_troll_chief'],
    summary: 'Besiege die Reifhexen, die die Kälte über die Zinnen bringen.',
    offer: 'Die Reifhexen haben die Leuchtfeuer gelöscht und die Trolle gerufen. Jetzt singen sie am Reiftor, und der Schnee wird jeden Tag tiefer. Erschlag zehn von ihnen. Dann hört das Singen auf.',
    progressText: 'Die Reifhexen halten sich an den Hängen zum Reiftor auf.',
    completeText: 'Es schneit weniger. Hörst du das? Das ist Stille. Hier oben ist Stille das schönste Geräusch.',
    objectives: [{ id: 'witches', text: 'Reifhexen besiegt', count: 10, kind: 'kill', target: 'rime_witch', zone: 'frostspire' }],
    rewards: { xp: Q(34, W.main), gold: 300, gear: [{ ilvl: 35, rarity: 'uncommon', slot: 'feet' }] },
  },
  q_rime_gate: {
    title: 'Das Reiftor', giver: 'jarl_eskil', main: true, level: 35, requires: ['q_rime_witches'],
    summary: 'Öffne das Reiftor und kämpfe dich in die Reifhöhlen.',
    offer: 'Hinter dem Reiftor liegen die Reifhöhlen. Mein Großvater ist dort hineingegangen und kam nicht wieder. Die Hexen sagen, dort schläft ein Wurm aus Eis. Geh hinein und zerschlag die Wächter der Höhlen.',
    progressText: 'Das Reiftor liegt oberhalb der Hexenhänge.',
    completeText: 'Du kommst aus den Reifhöhlen zurück? Dann ist der Wurm echt. Meine Großmutter hatte recht, und ich schulde ihr eine Entschuldigung.',
    objectives: [
      { id: 'gate', text: 'Reiftor erreicht', count: 1, kind: 'reach', target: ['rime_gate', 'zone:rime_caverns'], zone: 'frostspire' },
      { id: 'guards', text: 'Wächter der Reifhöhlen zerschlagen', count: 10, kind: 'kill', target: ['ice_elemental', 'crystal_spider', 'frozen_knight'], zone: 'rime_caverns' },
    ],
    rewards: { xp: Q(35, W.main), gold: 320, gear: [{ ilvl: 36, rarity: 'uncommon', slot: 'hands' }] },
  },
  q_frost_wyrm: {
    title: 'Skalvyr, der Frostwurm', giver: 'jarl_eskil', main: true, level: 36, requires: ['q_rime_gate'],
    summary: 'Töte Skalvyr in seinem Hort und bring Eskil das Herz des Frostwurms.',
    offer: 'Skalvyr. Die Hexen singen seinen Namen. Er war einmal der Wächter dieser Berge, bevor die Krone ihn zu ihrem Diener machte. Erlöse ihn. Und bring mir sein Herz, damit Frosthold weiß, dass der Winter vorbei ist.',
    progressText: 'Skalvyrs Hort liegt am Grund der Reifhöhlen.',
    completeText: 'Im Herzen glüht ein Funke. Rot, nicht blau. Glut. Die Krone war auch in ihm. Marschall Corvane hält die letzte Bastion in der Glutöde, direkt vor dem Aschethron. Dort musst du hin.',
    objectives: [
      { id: 'boss', text: 'Skalvyr getötet', count: 1, kind: 'boss', target: 'frost_wyrm', zone: 'rime_caverns' },
      { id: 'heart', text: 'Herz des Frostwurms', count: 1, kind: 'collect', target: 'wyrm_heart', from: ['frost_wyrm'], zone: 'rime_caverns' },
    ],
    rewards: { xp: Q(36, W.boss), gold: 700, gear: [{ ilvl: 37, rarity: 'rare', slot: 'chest' }] },
  },
  q_the_wastes: {
    title: 'In die Glutöde', giver: 'jarl_eskil', turnInNpc: 'marshal_corvane', main: true, level: 36, requires: ['q_frost_wyrm'],
    summary: 'Steige in die Glutöde hinab und melde dich bei Marschall Corvane in der letzten Bastion.',
    offer: 'Hinter den Zinnen fällt das Land ab in die Glutöde. Dort regnet es Feuer statt Schnee. Corvane hält die letzte Bastion. Er ist der Letzte, der noch gegen den Thron steht. Geh zu ihm. Und komm lebend zurück, das Fass wartet.',
    progressText: 'Der Abstieg zur Glutöde beginnt am Südrand der Zinnen.',
    completeText: 'Eskil schickt dich. Dann bist du der, von dem die Raben erzählen. Willkommen in der letzten Bastion. Mehr gibt es nicht zwischen uns und dem Thron.',
    objectives: [{ id: 'travel', text: 'Letzte Bastion erreicht', count: 1, kind: 'reach', target: ['zone:ember_wastes', 'last_bastion'], zone: 'frostspire' }],
    rewards: { xp: Q(36, W.travel), gold: 220, items: [{ itemId: 'supreme_potion', qty: 3 }] },
  },

  // --- Sigrun (Nebenquests)
  q_frost_pelts: {
    title: 'Felle für den Winter', giver: 'hunter_sigrun', level: 31, requires: ['q_frost_pass'],
    summary: 'Bring Sigrun Frostwolfsfelle für die Wintermäntel.',
    offer: 'Die Hälfte von Frosthold friert in dünnen Mänteln. Frostwolfsfell ist das wärmste, was es gibt. Bring mir acht, und die Kinder erfrieren nicht diesen Winter.',
    progressText: 'Die Frostwölfe jagen auf den Straßen unterhalb von Frosthold.',
    completeText: 'Dicht und weiß. Daraus nähe ich vier Mäntel. Einer davon ist deiner, wenn du willst. Nein? Dann nimm das hier.',
    objectives: [{ id: 'pelts', text: 'Frostwolfsfelle gesammelt', count: 8, kind: 'collect', target: 'frost_pelt', from: ['frost_wolf'], zone: 'frostspire' }],
    rewards: { xp: Q(31, W.side), gold: 220, gear: [{ ilvl: 32, rarity: 'uncommon', slot: 'chest' }] },
  },
  q_snow_stalkers: {
    title: 'Jäger im Schnee', giver: 'hunter_sigrun', level: 32, requires: ['q_frost_pelts'],
    summary: 'Erlege die Schneepirscher, bevor sie weitere Jäger aus dem Hinterhalt reißen.',
    offer: 'Die Schneepirscher graben sich ein und warten. Wenn du sie siehst, ist es zu spät. Drei meiner Jäger haben sie schon geholt. Erlege zehn. Halte die Augen am Boden.',
    progressText: 'Die Schneepirscher lauern im tiefen Schnee am Wegrand.',
    completeText: 'Zehn. Und du hast noch alle Finger. Du bist ein besserer Jäger, als du aussiehst.',
    objectives: [{ id: 'stalkers', text: 'Schneepirscher erlegt', count: 10, kind: 'kill', target: 'snow_stalker', zone: 'frostspire' }],
    rewards: { xp: Q(32, W.side), gold: 230, gear: [{ ilvl: 33, rarity: 'uncommon', slot: 'weapon' }] },
  },
  q_troll_fat: {
    title: 'Trollfett', giver: 'hunter_sigrun', level: 33, requires: ['q_snow_stalkers'],
    summary: 'Sammle Trollfett, damit Frostholds Klingen nicht einfrieren.',
    offer: 'Bei dieser Kälte frieren Klingen in der Scheide fest. Trollfett hält sie frei. Stinkt, aber hält. Bring mir acht Brocken.',
    progressText: 'Die Eistrolle findest du in und vor den Trollhöhlen.',
    completeText: 'Riech mal. Nein, besser nicht. Jedes Schwert in Frosthold wird dir danken.',
    objectives: [{ id: 'fat', text: 'Trollfett gesammelt', count: 8, kind: 'collect', target: 'troll_fat', from: ['ice_troll'], zone: 'frostspire' }],
    rewards: { xp: Q(33, W.side), gold: 240, items: [{ itemId: 'supreme_mana', qty: 3 }] },
  },
  q_frozen_knights: {
    title: 'Die erfrorenen Ritter', giver: 'hunter_sigrun', level: 35, requires: ['q_troll_fat', 'q_rime_witches'],
    summary: 'Erlöse die erfrorenen Ritter in den Reifhöhlen.',
    offer: 'Mein Großvater führte die Ritter von Frosthold in die Reifhöhlen. Sie kamen nie zurück. Die Jäger sagen, sie stehen noch dort unten, im Eis, und bewegen sich. Erlöse sie. Vier waren es.',
    progressText: 'Die erfrorenen Ritter wandern durch die Reifhöhlen.',
    completeText: 'Sie ruhen jetzt. Ich werde ihre Namen in den Stein über dem Tor schlagen. Deinen auch, wenn du willst.',
    objectives: [{ id: 'knights', text: 'Erfrorene Ritter erlöst', count: 4, kind: 'kill', target: 'frozen_knight', zone: 'rime_caverns' }],
    rewards: { xp: Q(35, W.dungeonSide), gold: 280, gear: [{ ilvl: 36, rarity: 'rare', slot: 'head' }] },
  },
  q_crystal_silk: {
    title: 'Kristallseide', giver: 'hunter_sigrun', level: 36, requires: ['q_frozen_knights'],
    summary: 'Sammle Kristallseide von den Kristallspinnen der Reifhöhlen.',
    offer: 'Aus Kristallseide macht man Bogensehnen, die bei jeder Kälte halten. Die Spinnen in den Reifhöhlen spinnen sie. Bring mir vier Bündel, und ich spanne dir einen Bogen, wie ihn noch kein Jarl hatte.',
    progressText: 'Die Kristallspinnen hängen an den Decken der Reifhöhlen.',
    completeText: 'Sie klingt, wenn man sie zupft. Wie Glas. Das ist die beste Seide, die ich je gesehen habe.',
    objectives: [{ id: 'silk', text: 'Kristallseide gesammelt', count: 4, kind: 'collect', target: 'crystal_silk', from: ['crystal_spider'], zone: 'rime_caverns' }],
    rewards: { xp: Q(36, W.dungeonSide), gold: 300, gear: [{ ilvl: 37, rarity: 'rare', slot: 'ring' }] },
  },

  // ================================================================ Glutöde & Aschethron (36–40)
  q_wastes_wraiths: {
    title: 'Geister aus Asche', giver: 'marshal_corvane', main: true, level: 36, requires: ['q_the_wastes'],
    summary: 'Vernichte die Aschengeister, die die Bastion umkreisen.',
    offer: 'Die Aschengeister sind die Toten der letzten Schlacht. Sie wandern um unsere Mauern und rufen die Namen derer, die noch drinnen sind. Das zermürbt meine Leute mehr als jeder Angriff. Vernichte fünfzehn.',
    progressText: 'Die Aschengeister umkreisen die letzte Bastion.',
    completeText: 'Es ist ruhiger. Meine Wachen schauen wieder nach draußen statt auf ihre Füße. Das ist viel wert.',
    objectives: [{ id: 'wraiths', text: 'Aschengeister vernichtet', count: 15, kind: 'kill', target: 'ash_wraith', zone: 'ember_wastes' }],
    rewards: { xp: Q(36, W.kill), gold: 300, gear: [{ ilvl: 37, rarity: 'uncommon', slot: 'weapon' }] },
  },
  q_wastes_obelisks: {
    title: 'Die Glutobelisken', giver: 'marshal_corvane', main: true, level: 37, requires: ['q_wastes_wraiths'],
    summary: 'Lösche die drei Glutobelisken, die den Glutregen nähren.',
    offer: 'Der Feuerregen kommt nicht vom Himmel. Er kommt von drei Obelisken, die der Aschenfürst aufgestellt hat. Lösch ihr Feuer, und wir können wieder Patrouillen schicken, ohne dass sie verbrennen.',
    progressText: 'Die Glutobelisken glühen weithin sichtbar über der Öde.',
    completeText: 'Der Regen hört auf. Ich habe den Himmel über der Öde seit zehn Jahren nicht mehr gesehen. Er ist grau. Aber es ist ein Himmel.',
    objectives: [{ id: 'obelisks', text: 'Glutobelisken gelöscht', count: 3, kind: 'interact', target: ['ember_obelisk_1', 'ember_obelisk_2', 'ember_obelisk_3'], zone: 'ember_wastes' }],
    rewards: { xp: Q(37, W.main), gold: 320, gear: [{ ilvl: 38, rarity: 'uncommon', slot: 'chest' }] },
  },
  q_cinder_knights: {
    title: 'Die Schlackenritter', giver: 'marshal_corvane', main: true, level: 37, requires: ['q_wastes_obelisks'],
    summary: 'Besiege die Schlackenritter, die Garde des Aschenfürsten.',
    offer: 'Die Schlackenritter waren einmal meine Ritter. Der Fürst hat sie genommen und mit Glut gefüllt. Jetzt kämpfen sie für ihn. Erlöse zwölf von ihnen. Ich kannte jeden einzelnen.',
    progressText: 'Die Schlackenritter patrouillieren zwischen der Bastion und dem Kolossfeld.',
    completeText: 'Zwölf. Ich werde ihre Namen nicht aussprechen. Aber ich werde sie nie vergessen. Danke.',
    objectives: [{ id: 'knights', text: 'Schlackenritter besiegt', count: 12, kind: 'kill', target: 'cinder_knight', zone: 'ember_wastes' }],
    rewards: { xp: Q(37, W.main), gold: 340, gear: [{ ilvl: 38, rarity: 'uncommon', slot: 'head' }] },
  },
  q_colossus: {
    title: 'Der Glutkoloss', giver: 'marshal_corvane', main: true, level: 38, requires: ['q_cinder_knights'],
    summary: 'Bring den Glutkoloss auf dem Kolossfeld zu Fall und bring Corvane seinen Kern.',
    offer: 'Zwischen uns und dem Thron steht der Glutkoloss. Er bewacht das Tor, seit ich hier bin. Keiner von uns ist ihm nahe gekommen und hat es überlebt. Du wirst der Erste sein. Bring mir seinen Kern, dann marschieren wir.',
    progressText: 'Der Glutkoloss steht auf dem Kolossfeld vor dem Throntor.',
    completeText: 'Der Kern … er glüht wie eine kleine Sonne. Der Weg zum Thron ist frei. Zum ersten Mal in zehn Jahren.',
    objectives: [
      { id: 'field', text: 'Kolossfeld erreicht', count: 1, kind: 'reach', target: ['colossus_field'], zone: 'ember_wastes' },
      { id: 'colossus', text: 'Glutkoloss gefällt', count: 1, kind: 'kill', target: 'waste_colossus', zone: 'ember_wastes' },
      { id: 'core', text: 'Kern des Glutkolosses', count: 1, kind: 'collect', target: 'colossus_core', from: ['waste_colossus'], zone: 'ember_wastes' },
    ],
    rewards: { xp: Q(38, W.elite), gold: 480, gear: [{ ilvl: 39, rarity: 'rare', slot: 'weapon' }] },
  },
  q_throne_gate: {
    title: 'Vor dem Thron', giver: 'marshal_corvane', main: true, level: 39, requires: ['q_colossus'],
    summary: 'Durchbrich das Throntor und kämpfe dich durch die Thronwache.',
    offer: 'Das Throntor ist offen. Dahinter liegt der Aschethron, und dahinter Malgareth selbst. Die Thronwache steht in den Hallen. Schlag dich durch, zehn von ihnen, und halte das Tor für meine Leute offen.',
    progressText: 'Das Throntor liegt am Ende des Kolossfelds.',
    completeText: 'Du hast das Tor gehalten. Meine Leute stehen jetzt davor. Egal was passiert, der Weg zurück bleibt offen.',
    objectives: [
      { id: 'gate', text: 'Throntor erreicht', count: 1, kind: 'reach', target: ['throne_gate', 'zone:ashen_throne'], zone: 'ember_wastes' },
      { id: 'guards', text: 'Thronwachen besiegt', count: 10, kind: 'kill', target: ['throne_guard', 'ash_priest', 'ember_hellhound'], zone: 'ashen_throne' },
    ],
    rewards: { xp: Q(39, W.main), gold: 380, gear: [{ ilvl: 40, rarity: 'uncommon', slot: 'feet' }] },
  },
  q_throne_sentinel: {
    title: 'Der Wächter des Throns', giver: 'marshal_corvane', main: true, level: 39, requires: ['q_throne_gate'],
    summary: 'Besiege den Wächter, der den Weg zur Thronhalle versperrt.',
    offer: 'Vor der Thronhalle steht ein letzter Wächter. Meine Späher sagen, er war einmal ein König wie Ulgrim. Jetzt ist er nur noch Glut und Rüstung. Besiege ihn, dann steht nur noch Malgareth zwischen dir und dem Ende.',
    progressText: 'Der Wächter des Throns steht vor der Thronhalle.',
    completeText: 'Du stehst noch. Dann gibt es jetzt nur noch einen. Ruh dich aus, schärf deine Klinge, und dann bring es zu Ende.',
    objectives: [{ id: 'sentinel', text: 'Wächter des Throns besiegt', count: 1, kind: 'kill', target: 'throne_sentinel', zone: 'ashen_throne' }],
    rewards: { xp: Q(39, W.elite), gold: 500, gear: [{ ilvl: 40, rarity: 'rare', slot: 'chest' }] },
  },
  q_ash_sovereign: {
    title: 'Der Aschenfürst', giver: 'marshal_corvane', main: true, level: 40, requires: ['q_throne_sentinel'],
    summary: 'Stürze Malgareth, den Aschenfürsten, und nimm ihm die Flammenkrone.',
    offer: 'Malgareth. Der Aschenfürst. Er hat Varkhul gerufen, Ignaroth geschickt, Khar gekrönt, Mutter Fäulnis gezüchtet und Skalvyr versklavt. Alles für seine Krone. Geh in die Thronhalle und nimm sie ihm. Dann ist es vorbei.',
    progressText: 'Malgareth erwartet dich in der Thronhalle.',
    completeText: 'Die Flammenkrone … Sie ist kalt. Zum ersten Mal seit tausend Jahren. Du hast getan, was keiner vor dir geschafft hat. Das Land ist frei. Und die Asche hört auf zu fallen. Bring die Krone zu Hale. Er hat diesen Weg mit dir begonnen.',
    objectives: [
      { id: 'boss', text: 'Malgareth gestürzt', count: 1, kind: 'boss', target: 'ash_sovereign', zone: 'ashen_throne' },
      { id: 'crown', text: 'Flammenkrone', count: 1, kind: 'collect', target: 'sovereign_crown', from: ['ash_sovereign'], zone: 'ashen_throne' },
    ],
    rewards: { xp: Q(40, W.finale), gold: 1500, gear: [{ ilvl: 40, rarity: 'epic', slot: 'weapon' }] },
  },

  // --- Aldo (Nebenquests)
  q_magma_serpents: {
    title: 'Schuppen aus Magma', giver: 'pilgrim_aldo', level: 36, requires: ['q_the_wastes'],
    summary: 'Sammle Magmaschuppen für Aldos Schutzamulette.',
    offer: 'Ich pilgere zum Thron, um für die Toten zu beten. Aber die Glutöde brennt. Magmaschuppen schützen vor dem Feuer, sagen die Alten. Bring mir sechs. Dann mache ich Amulette für uns beide.',
    progressText: 'Die Magmaschlangen schwimmen durch die Lavaflüsse der Öde.',
    completeText: 'Heiß! Heiß! Aber gut. Mit diesen Schuppen gehe ich durch jedes Feuer.',
    objectives: [{ id: 'scales', text: 'Magmaschuppen gesammelt', count: 6, kind: 'collect', target: 'magma_scale', from: ['magma_serpent'], zone: 'ember_wastes' }],
    rewards: { xp: Q(36, W.side), gold: 280, gear: [{ ilvl: 37, rarity: 'uncommon', slot: 'amulet' }] },
  },
  q_adept_sigils: {
    title: 'Siegel der Adepten', giver: 'pilgrim_aldo', level: 37, requires: ['q_magma_serpents'],
    summary: 'Nimm den Glutadepten ihre Siegel ab.',
    offer: 'Die Adepten verteilen Siegel an jeden, der sich dem Fürsten beugt. Mit einem Siegel darf man durch die Öde, ohne verbrannt zu werden. Ich will keins. Ich will, dass sie keins mehr verteilen. Bring mir acht.',
    progressText: 'Die Glutadepten predigen zwischen den Obelisken.',
    completeText: 'Acht Siegel weniger. Acht Menschen weniger, die sich beugen müssen. Das ist eine gute Pilgerfahrt.',
    objectives: [{ id: 'sigils', text: 'Adeptensiegel erbeutet', count: 8, kind: 'collect', target: 'adept_sigil', from: ['ember_cultist_adept'], zone: 'ember_wastes' }],
    rewards: { xp: Q(37, W.side), gold: 300, items: [{ itemId: 'supreme_potion', qty: 4 }] },
  },
  q_pilgrim_relics: {
    title: 'Die verlorenen Pilger', giver: 'pilgrim_aldo', level: 38, requires: ['q_adept_sigils'],
    summary: 'Birg die Reliquien der Pilger, die von den Aschengeistern verschlungen wurden.',
    offer: 'Viele Pilger kamen vor mir. Keiner kam an. Die Aschengeister tragen noch ihre Reliquien. Bring mir sechs, damit ich sie am Thron niederlegen kann, für jene, die es nicht geschafft haben.',
    progressText: 'Die Aschengeister wandern um die Bastion und über das Kolossfeld.',
    completeText: 'Jede davon hat eine Geschichte. Ich werde sie alle erzählen, wenn ich am Thron bin.',
    objectives: [{ id: 'relics', text: 'Pilgerreliquien geborgen', count: 6, kind: 'collect', target: 'pilgrim_relic', from: ['ash_wraith'], zone: 'ember_wastes' }],
    rewards: { xp: Q(38, W.side), gold: 320, gear: [{ ilvl: 39, rarity: 'rare', slot: 'amulet' }] },
  },
  q_hellhounds: {
    title: 'Die Höllenhunde', giver: 'pilgrim_aldo', level: 39, requires: ['q_pilgrim_relics', 'q_throne_gate'],
    summary: 'Erschlage die Glutdoggen in den Hallen des Aschethrons.',
    offer: 'In den Hallen des Throns jagen Glutdoggen. Sie haben die letzten Pilger gerissen, die bis dorthin kamen. Erschlag alle drei. Dann kann ich meinen Weg zu Ende gehen.',
    progressText: 'Die Glutdoggen jagen in den Hallen des Aschethrons.',
    completeText: 'Der Weg ist frei. Nach so vielen Jahren. Ich gehe morgen früh. Danke, Freund.',
    objectives: [{ id: 'hounds', text: 'Glutdoggen erschlagen', count: 3, kind: 'kill', target: 'ember_hellhound', zone: 'ashen_throne' }],
    rewards: { xp: Q(39, W.dungeonSide), gold: 340, gear: [{ ilvl: 40, rarity: 'rare', slot: 'feet' }] },
  },
  q_ash_prayers: {
    title: 'Gebete aus Asche', giver: 'pilgrim_aldo', level: 39, requires: ['q_hellhounds'],
    summary: 'Nimm den Aschepriestern ihre Gebete ab.',
    offer: 'Die Aschepriester beten jeden Tag zu Malgareth. Ihre Gebete sind auf Haut geschrieben. Ich will sie verbrennen, eines nach dem anderen, und dafür beten, dass niemand mehr so beten muss. Bring mir drei.',
    progressText: 'Die Aschepriester halten sich in den Hallen des Aschethrons auf.',
    completeText: 'Sie brennen schlecht. Wie alles, was mit Angst geschrieben wurde. Aber sie brennen.',
    objectives: [{ id: 'prayers', text: 'Aschengebete erbeutet', count: 3, kind: 'collect', target: 'ash_prayer', from: ['ash_priest'], zone: 'ashen_throne' }],
    rewards: { xp: Q(39, W.dungeonSide), gold: 360, gear: [{ ilvl: 40, rarity: 'rare', slot: 'ring' }] },
  },

  // ================================================================ Nachspiel
  q_homecoming: {
    title: 'Heimkehr', giver: 'marshal_corvane', turnInNpc: 'commander_hale', main: true, level: 40, requires: ['q_ash_sovereign'],
    summary: 'Bring die Nachricht vom Fall des Aschenfürsten zu Kommandant Hale in die Rauhwacht.',
    offer: 'Hale hat dich losgeschickt, also soll er es von dir hören, nicht von einem Boten. Nimm den langen Weg zurück: durch die Zinnen, die Marsch, die Steppe. Sieh dir an, was du verändert hast. Dann sag ihm, dass es vorbei ist.',
    progressText: 'Der Weg zurück zur Rauhwacht führt durch alle Lande, die du befreit hast.',
    completeText: 'Du lebst. Und Malgareth nicht. Ich habe dich in die Steppe geschickt, weil ich niemanden sonst hatte. Heute weiß ich, dass ich keinen Besseren hätte schicken können. Ruh dich aus. Hinter dem Thron gibt es noch Länder, die keiner von uns kennt. Irgendwann wirst du sie sehen.',
    objectives: [{ id: 'travel', text: 'Rauhwacht erreicht', count: 1, kind: 'reach', target: ['zone:cinder_peaks', 'rookwatch'], zone: 'ember_wastes' }],
    rewards: { xp: Q(39, W.epilogue), gold: 2500, items: [{ itemId: 'supreme_potion', qty: 5 }] },
  },

  // ================================================================ Weitere Nebenquests (Lücken zwischen den Hauptquests)
  // --- Aschensteppe
  q_vulture_cull: {
    title: 'Aasfresser über der Straße', giver: 'trader_imra', level: 22, requires: ['q_new_horizons'],
    summary: 'Vertreibe die Aschegeier, die Imras Karawanen bis zum Außenposten folgen.',
    offer: 'Die Geier folgen jeder Karawane. Sie warten, bis ein Zugtier stolpert, und dann warten sie nicht mehr. Meine Treiber haben Angst vor dem Himmel. Hol zwölf von ihnen herunter.',
    progressText: 'Die Aschegeier kreisen über der Straße zum Außenposten.',
    completeText: 'Der Himmel ist leer. Meine Treiber schauen wieder nach vorn statt nach oben. Das spart mir Zugtiere und dir eine Menge Ärger mit mir.',
    objectives: [{ id: 'vultures', text: 'Aschegeier erlegt', count: 12, kind: 'kill', target: 'ash_vulture', zone: 'ashen_steppe' }],
    rewards: { xp: Q(22, W.side), gold: 130, items: [{ itemId: 'superior_potion', qty: 3 }] },
  },
  q_imra_cargo: {
    title: 'Gestohlene Ballen', giver: 'trader_imra', level: 23, requires: ['q_vulture_cull'],
    summary: 'Hol Imras Gewürzballen von den Plünderern zurück.',
    offer: 'Letzte Woche haben die Plünderer eine ganze Ladung Gewürze geraubt. Gewürze! Was will ein Plünderer mit Safran? Sie tragen die Ballen noch mit sich herum, weil sie keiner kaufen will. Bring mir sechs zurück.',
    progressText: 'Die Steppenplünderer schleppen Imras Gewürzballen mit sich.',
    completeText: 'Riechst du das? Safran, Zimt, Glutpfeffer. Damit bezahle ich einen Monat Miete am Außenposten. Hier, dein Anteil, und sag keinem, wie viel er ist.',
    objectives: [{ id: 'bales', text: 'Gewürzballen zurückgeholt', count: 6, kind: 'collect', target: 'spice_bale', from: ['steppe_raider'], zone: 'ashen_steppe' }],
    rewards: { xp: Q(23, W.side), gold: 220, gear: [{ ilvl: 24, rarity: 'uncommon', slot: 'amulet' }] },
  },
  q_scattered_riders: {
    title: 'Versprengte Reiter', giver: 'captain_varra', level: 24, requires: ['q_steppe_warlord'],
    summary: 'Treib die Reiter auseinander, die sich nach Khars Fall neu sammeln.',
    offer: 'Khar ist tot, aber seine Reiter sind es nicht. Sie sammeln sich in kleinen Gruppen und suchen einen neuen Anführer. Lass sie keinen finden. Fünfzehn weniger, und die Stämme wissen, wohin der Wind weht.',
    progressText: 'Die versprengten Reiter lagern verstreut in der Steppe.',
    completeText: 'Die letzten sind nach Süden geflohen. Ohne Horn, ohne Banner, ohne Fürst. Die Steppe gehört wieder den Nomaden.',
    objectives: [{ id: 'riders', text: 'Versprengte Reiter besiegt', count: 15, kind: 'kill', target: ['steppe_raider', 'raider_archer'], zone: 'ashen_steppe' }],
    rewards: { xp: Q(24, W.side), gold: 200, gear: [{ ilvl: 25, rarity: 'uncommon', slot: 'feet' }] },
  },

  // --- Faulmarsch
  q_moll_crates: {
    title: 'Kisten im Schlamm', giver: 'trader_moll', level: 26, requires: ['q_into_the_marsh'],
    summary: 'Hol Molls Warenkisten zurück, die die Moorlauerer in den Schlamm gezogen haben.',
    offer: 'Mein Boot ist gekentert. Nicht meine Schuld, ein Lauerer hat dran gezogen. Jetzt liegen meine Kisten im Schlamm, und die Lauerer schleppen sie in ihre Nester, weil sie glänzen. Bring mir sechs zurück, bevor sie verrotten.',
    progressText: 'Die Moorlauerer horten Molls Kisten in ihren Nestern am Ufer.',
    completeText: 'Nass, verbeult, aber voll. Meine Tränke haben überlebt. Das ist mehr, als ich von meinem Boot sagen kann.',
    objectives: [{ id: 'crates', text: 'Warenkisten geborgen', count: 6, kind: 'collect', target: 'moll_crate', from: ['bog_lurker'], zone: 'blighted_marsh' }],
    rewards: { xp: Q(26, W.side), gold: 230, items: [{ itemId: 'superior_potion', qty: 4 }] },
  },
  q_toad_wall: {
    title: 'Kröten an der Mauer', giver: 'warden_thane', level: 27, requires: ['q_marsh_totems'],
    summary: 'Erlege die Seuchenkröten, die sich an der Mauer der Mirefeste sammeln.',
    offer: 'Seit die Totems brennen, kriechen die Seuchenkröten aus dem Nebel an meine Mauer. Ihr Gift frisst den Mörtel. Ich habe Wachen, aber keine, die eine Kröte anfassen wollen. Erschlag zwölf.',
    progressText: 'Die Seuchenkröten hocken im Schilf rund um die Mirefeste.',
    completeText: 'Die Mauer steht, und meine Wachen haben aufgehört, sich zu kratzen. Wasch dir die Hände, bevor du hier etwas anfasst.',
    objectives: [{ id: 'toads', text: 'Seuchenkröten erlegt', count: 12, kind: 'kill', target: 'plague_toad', zone: 'blighted_marsh' }],
    rewards: { xp: Q(27, W.side), gold: 240, gear: [{ ilvl: 28, rarity: 'uncommon', slot: 'hands' }] },
  },
  q_black_market: {
    title: 'Faule Geschäfte', giver: 'trader_moll', level: 28, requires: ['q_moll_crates', 'q_marsh_shamans'],
    summary: 'Die Faulschamanen überfallen Händler auf den Stegen. Mach dem ein Ende.',
    offer: 'Die Schamanen lassen sich ihre Götzen bezahlen. Von Händlern. Mit Händlern, wenn du verstehst. Zwei meiner Kollegen sind auf den Stegen verschwunden. Erschlag acht Schamanen, dann wird das Geschäft wieder sicher.',
    progressText: 'Die Faulschamanen lauern an den Stegen zum versunkenen Dorf.',
    completeText: 'Auf den Stegen ist es ruhig. Ich habe drei Händler gesehen, die heute lebend angekommen sind. Ein Rekord. Nimm das, du hast es verdient.',
    objectives: [{ id: 'shamans', text: 'Faulschamanen besiegt', count: 8, kind: 'kill', target: 'rot_shaman', zone: 'blighted_marsh' }],
    rewards: { xp: Q(28, W.side), gold: 260, gear: [{ ilvl: 29, rarity: 'rare', slot: 'amulet' }] },
  },
  q_deep_mist: {
    title: 'Tiefer in den Nebel', giver: 'warden_thane', level: 29, requires: ['q_sunken_village'],
    summary: 'Halte die Stege zum Sporenschlund frei, damit Thanes Späher durchkommen.',
    offer: 'Meine Späher müssen bis zum Sporenschlund, aber auf den Stegen wimmelt es von Getier. Lauerer, Egel, Kröten, alles, was beißt. Mach zwanzig davon unschädlich. Dann schicke ich meine Leute los.',
    progressText: 'Die Stege zum Sporenschlund führen durch den tiefsten Nebel der Marsch.',
    completeText: 'Meine Späher sind durch. Sie sagen, aus dem Schlund steigt ein Leuchten, das nicht von dieser Welt ist. Ich glaube ihnen. Leider.',
    objectives: [{ id: 'beasts', text: 'Kreaturen auf den Stegen besiegt', count: 20, kind: 'kill', target: ['bog_lurker', 'swamp_leech', 'plague_toad'], zone: 'blighted_marsh' }],
    rewards: { xp: Q(29, W.side), gold: 280, gear: [{ ilvl: 30, rarity: 'uncommon', slot: 'head' }] },
  },

  // --- Frostzinnen
  q_fenn_claws: {
    title: 'Krallen für den Handel', giver: 'trader_fenn', level: 31, requires: ['q_frost_pass'],
    summary: 'Bring Fenn Pirscherkrallen. In den Städten des Südens zahlt man gut dafür.',
    offer: 'Weißt du, was eine Schneepirscherkralle im Süden kostet? Ich auch nicht genau, aber viel. Die Reichen hängen sie sich um den Hals. Bring mir sechs, dann teilen wir den Gewinn. Ehrlich.',
    progressText: 'Die Schneepirscher jagen an den Hängen oberhalb von Frosthold.',
    completeText: 'Schöne Krallen. Scharf, weiß, unversehrt. Die Reichen werden sich darum prügeln. Hier ist dein Anteil, und der ist wirklich ehrlich. Fast.',
    objectives: [{ id: 'claws', text: 'Pirscherkrallen gesammelt', count: 6, kind: 'collect', target: 'stalker_claw', from: ['snow_stalker'], zone: 'frostspire' }],
    rewards: { xp: Q(31, W.side), gold: 300, items: [{ itemId: 'supreme_potion', qty: 3 }] },
  },
  q_witch_charms: {
    title: 'Hexenzeichen', giver: 'trader_fenn', level: 32, requires: ['q_fenn_claws'],
    summary: 'Nimm den Reifhexen ihre Frostzeichen ab, bevor sie Frosthold verfluchen.',
    offer: 'Die Reifhexen hängen Zeichen an die Bäume rund um Frosthold. Wer darunter durchgeht, friert von innen. Ich verkaufe warme Sachen, aber dagegen hilft keine Wolle. Bring mir fünf ihrer Zeichen, ich werfe sie in die Esse.',
    progressText: 'Die Reifhexen tragen ihre Zeichen bei sich, an Schnüren aus Eis.',
    completeText: 'Sie schmelzen nicht einmal im Feuer. Ich werfe sie in die Schlucht. Soll sich das Eis darum kümmern.',
    objectives: [{ id: 'charms', text: 'Frostzeichen erbeutet', count: 5, kind: 'collect', target: 'witch_charm', from: ['rime_witch'], zone: 'frostspire' }],
    rewards: { xp: Q(32, W.side), gold: 320, gear: [{ ilvl: 33, rarity: 'rare', slot: 'ring' }] },
  },
  q_white_hunt: {
    title: 'Die weiße Jagd', giver: 'hunter_sigrun', level: 33, requires: ['q_snow_stalkers'],
    summary: 'Geh mit Sigrun auf die große Winterjagd: Frostwölfe und Schneepirscher.',
    offer: 'Einmal im Jahr jagen die Frostholder, bis der Schnee rot ist. Dieses Jahr war keiner da, der jagen konnte. Du bist da. Fünfzehn Wölfe oder Pirscher, dann hat Frosthold Fleisch für den Winter.',
    progressText: 'Wölfe und Pirscher streifen über die Hänge der Frostzinnen.',
    completeText: 'Fleisch für den ganzen Winter. Heute Abend wird in der Halle gesungen, und dein Name kommt in der dritten Strophe vor. Die erste und zweite gehören den Toten.',
    objectives: [{ id: 'hunt', text: 'Wölfe und Pirscher erlegt', count: 15, kind: 'kill', target: ['frost_wolf', 'snow_stalker'], zone: 'frostspire' }],
    rewards: { xp: Q(33, W.side), gold: 330, gear: [{ ilvl: 34, rarity: 'uncommon', slot: 'chest' }] },
  },

  // --- Glutöde
  q_bastion_supplies: {
    title: 'Nachschub für die Bastion', giver: 'quartermaster_ryn', level: 37, requires: ['q_the_wastes'],
    summary: 'Die Aschegeister haben Ryns Nachschub zerstreut. Sammle die Vorräte wieder ein.',
    offer: 'Der letzte Nachschubzug kam nie an. Die Aschegeister haben ihn auf der Straße zerrissen und tragen die Reste mit sich herum, als wüssten sie noch, wofür sie gut sind. Bring mir sechs Vorratsbündel zurück.',
    progressText: 'Die Aschegeister schweben über der Straße zur Bastion.',
    completeText: 'Brot, Verbände, Pfeilspitzen. Nichts davon ist mehr warm, aber alles ist da. Die Bastion hält eine Woche länger. Das ist hier eine Ewigkeit.',
    objectives: [{ id: 'supplies', text: 'Vorratsbündel geborgen', count: 6, kind: 'collect', target: 'bastion_supplies', from: ['ash_wraith'], zone: 'ember_wastes' }],
    rewards: { xp: Q(37, W.side), gold: 380, items: [{ itemId: 'supreme_potion', qty: 4 }] },
  },
  q_serpent_pits: {
    title: 'Die Schlangengruben', giver: 'quartermaster_ryn', level: 37, requires: ['q_bastion_supplies'],
    summary: 'Erlege die Magmaschlangen, die die Wasserstellen der Bastion vergiften.',
    offer: 'Die Magmaschlangen nisten in den Gruben, aus denen wir unser Wasser holen. Das Wasser kocht, wenn sie darin schwimmen. Erschlag zehn, dann trinken wir wieder etwas anderes als Asche.',
    progressText: 'Die Magmaschlangen nisten in den Gruben vor der Bastion.',
    completeText: 'Das Wasser ist trüb, aber kalt. Kalt! Ich hatte vergessen, wie sich das anfühlt.',
    objectives: [{ id: 'serpents', text: 'Magmaschlangen erlegt', count: 10, kind: 'kill', target: 'magma_serpent', zone: 'ember_wastes' }],
    rewards: { xp: Q(37, W.side), gold: 400, gear: [{ ilvl: 38, rarity: 'uncommon', slot: 'feet' }] },
  },
  q_adept_hunt: {
    title: 'Die Adepten der Krone', giver: 'marshal_corvane', level: 38, requires: ['q_wastes_obelisks'],
    summary: 'Erschlag die Glutadepten, die neue Obelisken entzünden wollen.',
    offer: 'Die Obelisken sind aus, aber die Adepten haben es noch nicht begriffen. Sie schleichen nachts hinaus und versuchen, sie wieder zu entzünden. Ich will, dass keiner von ihnen zurückkommt. Zehn genügen, um es den anderen klarzumachen.',
    progressText: 'Die Glutadepten sammeln sich bei den erloschenen Obelisken.',
    completeText: 'Die Obelisken bleiben kalt. Meine Wachen haben in der letzten Nacht nicht einen einzigen Funken gesehen. Gut gemacht.',
    objectives: [{ id: 'adepts', text: 'Glutadepten besiegt', count: 10, kind: 'kill', target: 'ember_cultist_adept', zone: 'ember_wastes' }],
    rewards: { xp: Q(38, W.side), gold: 420, gear: [{ ilvl: 39, rarity: 'rare', slot: 'amulet' }] },
  },

  // ================================================================ Kopfgelder (wiederholbar)
  q_bounty_steppe: {
    title: 'Kopfgeld: Aschensteppe', giver: 'trader_imra', repeatable: true, level: 22, requires: ['q_new_horizons'],
    summary: 'Imra zahlt für jeden Feind weniger in der Steppe.',
    offer: 'Jede Karawane, die hier durchkommt, bringt mir Geld. Jeder Plünderer, der sie überfällt, kostet mich Geld. Zwanzig Feinde weniger, und ich teile den Gewinn mit dir. Jedes Mal.',
    progressText: 'Zwanzig Feinde in der Aschensteppe. Egal welche.',
    completeText: 'Die Karawanen danken es dir. Ich auch. Hier, dein Anteil.',
    objectives: [{ id: 'kills', text: 'Feinde in der Steppe besiegt', count: 20, kind: 'kill', target: ['steppe_raider', 'raider_archer', 'dust_hyena', 'ash_vulture'], zone: 'ashen_steppe' }],
    rewards: { xp: Q(22, W.bounty), gold: 150, items: [{ itemId: 'superior_potion', qty: 2 }] },
  },
  q_bounty_marsh: {
    title: 'Kopfgeld: Faulmarsch', giver: 'trader_moll', repeatable: true, level: 28, requires: ['q_into_the_marsh'],
    summary: 'Moll zahlt für jede Kreatur weniger in der Marsch.',
    offer: 'Ich verkaufe Tränke an Leute, die morgen tot sind. Das ist schlecht fürs Geschäft. Zwanzig Viecher weniger in der Marsch, und du bekommst deinen Lohn.',
    progressText: 'Zwanzig Kreaturen in der Faulmarsch.',
    completeText: 'Meine Kunden leben länger. Das freut mich. Und meinen Geldbeutel.',
    objectives: [{ id: 'kills', text: 'Kreaturen in der Marsch besiegt', count: 20, kind: 'kill', target: ['bog_lurker', 'rot_shaman', 'swamp_leech', 'plague_toad'], zone: 'blighted_marsh' }],
    rewards: { xp: Q(28, W.bounty), gold: 190, items: [{ itemId: 'superior_potion', qty: 2 }] },
  },
  q_bounty_frost: {
    title: 'Kopfgeld: Frostzinnen', giver: 'trader_fenn', repeatable: true, level: 33, requires: ['q_frost_pass'],
    summary: 'Fenn zahlt für jede Bestie weniger auf den Zinnen.',
    offer: 'Der Jarl zahlt mir für jede Bestie, die nicht mehr durch unsere Straßen streift. Ich zahle dir. Zwanzig. Du kennst das.',
    progressText: 'Zwanzig Bestien auf den Frostzinnen.',
    completeText: 'Gute Arbeit. Frosthold schläft ruhiger, und ich zähle Münzen. Alle gewinnen.',
    objectives: [{ id: 'kills', text: 'Bestien auf den Zinnen besiegt', count: 20, kind: 'kill', target: ['ice_troll', 'frost_wolf', 'rime_witch', 'snow_stalker'], zone: 'frostspire' }],
    rewards: { xp: Q(33, W.bounty), gold: 230, items: [{ itemId: 'supreme_potion', qty: 2 }] },
  },
  q_bounty_wastes: {
    title: 'Kopfgeld: Glutöde', giver: 'quartermaster_ryn', repeatable: true, level: 38, requires: ['q_the_wastes'],
    summary: 'Ryn zahlt Sold für jeden Feind der Bastion.',
    offer: 'Die Bastion zahlt Sold für jeden Feind, der nicht mehr gegen unsere Mauern rennt. Zwanzig, und das Gold gehört dir. So oft du willst.',
    progressText: 'Zwanzig Feinde in der Glutöde.',
    completeText: 'Sold ist Sold. Du hast ihn dir verdient.',
    objectives: [{ id: 'kills', text: 'Feinde in der Glutöde besiegt', count: 20, kind: 'kill', target: ['ash_wraith', 'cinder_knight', 'magma_serpent', 'ember_cultist_adept'], zone: 'ember_wastes' }],
    rewards: { xp: Q(38, W.bounty), gold: 270, items: [{ itemId: 'supreme_potion', qty: 2 }] },
  },
  // Kleinere Jagdaufträge je Region (wiederholbar, andere Ziele als das Kopfgeld)
  q_hunt_steppe: {
    title: 'Jagdrecht der Nomaden', giver: 'nomad_kesh', repeatable: true, level: 23, requires: ['q_steppe_hyenas'],
    summary: 'Kesh teilt sein Jagdrecht mit dir: Hyänen und Geier.',
    offer: 'Die Steppe gibt, und die Steppe nimmt. Die Hyänen und Geier nehmen gerade mehr, als sie sollten. Zwölf weniger, und ich teile, was mein Stamm entbehren kann. Komm wieder, wann du willst.',
    progressText: 'Hyänen und Aschegeier in der offenen Steppe.',
    completeText: 'Gute Jagd. Der Wind ist auf deiner Seite.',
    objectives: [{ id: 'hunt', text: 'Hyänen und Geier erlegt', count: 12, kind: 'kill', target: ['dust_hyena', 'ash_vulture'], zone: 'ashen_steppe' }],
    rewards: { xp: Q(23, W.hunt), gold: 100, items: [{ itemId: 'steppe_jerky', qty: 3 }] },
  },
  q_hunt_marsh: {
    title: 'Frische Zutaten', giver: 'alchemist_brisa', repeatable: true, level: 28, requires: ['q_marsh_leeches'],
    summary: 'Brisa braucht ständig frische Egel und Kröten.',
    offer: 'Meine Tränke werden nicht von allein. Zwölf Egel oder Kröten, frisch erlegt, und ich zahle in Gold und Glas. Und ja, du darfst jederzeit wiederkommen. Bitte komm wieder.',
    progressText: 'Sumpfegel und Seuchenkröten in der Faulmarsch.',
    completeText: 'Frisch und eklig. Genau so, wie ich sie mag.',
    objectives: [{ id: 'hunt', text: 'Egel und Kröten erlegt', count: 12, kind: 'kill', target: ['swamp_leech', 'plague_toad'], zone: 'blighted_marsh' }],
    rewards: { xp: Q(28, W.hunt), gold: 150, items: [{ itemId: 'superior_potion', qty: 2 }] },
  },
  q_hunt_frost: {
    title: 'Winterjagd', giver: 'hunter_sigrun', repeatable: true, level: 33, requires: ['q_frost_pelts'],
    summary: 'Sigrun jagt jeden Tag. Jag mit.',
    offer: 'Frosthold isst, was die Jäger bringen. Zwölf Wölfe oder Pirscher, dann isst Frosthold heute. Morgen fragen wir wieder.',
    progressText: 'Frostwölfe und Schneepirscher an den Hängen.',
    completeText: 'Frosthold isst heute. Danke, Jägerin. Oder Jäger. Im Schnee sehen wir alle gleich aus.',
    objectives: [{ id: 'hunt', text: 'Wölfe und Pirscher erlegt', count: 12, kind: 'kill', target: ['frost_wolf', 'snow_stalker'], zone: 'frostspire' }],
    rewards: { xp: Q(33, W.hunt), gold: 170, items: [{ itemId: 'supreme_potion', qty: 1 }] },
  },
  q_hunt_wastes: {
    title: 'Die Pilgerstraße', giver: 'pilgrim_aldo', repeatable: true, level: 38, requires: ['q_magma_serpents'],
    summary: 'Halte die Pilgerstraße frei von Geistern und Schlangen.',
    offer: 'Es kommen wieder Pilger. Nicht viele, aber sie kommen. Und die Straße ist voller Aschegeister und Schlangen. Zwölf weniger, und ein paar mehr kommen an. Ich bete für dich, jedes Mal.',
    progressText: 'Aschegeister und Magmaschlangen entlang der Pilgerstraße.',
    completeText: 'Die Straße ist frei, für heute. Morgen kommen neue. Und neue Pilger.',
    objectives: [{ id: 'hunt', text: 'Geister und Schlangen besiegt', count: 12, kind: 'kill', target: ['ash_wraith', 'magma_serpent'], zone: 'ember_wastes' }],
    rewards: { xp: Q(38, W.hunt), gold: 190, items: [{ itemId: 'supreme_potion', qty: 1 }] },
  },
};

// Gesprächszeilen der neuen NPCs (Namen legt Thread B als content 'npc' an; hier Rückfall)
export const NPC_LINES_40 = {
  captain_varra: {
    name: 'Hauptfrau Varra', idle: 'Halt die Klinge bereit. In der Steppe kommt der Tod auf vier Beinen.', bank: true,
    lines: [
      [null, 'Halt die Klinge bereit. In der Steppe kommt der Tod auf vier Beinen, und meistens auf mehr als einem Pferd.'],
      ['q_steppe_banners', 'Die Stämme reden über dich. Die Hälfte will dich töten, die andere Hälfte will dir folgen. Beides ist ein gutes Zeichen.'],
      ['q_steppe_warlord', 'Khars Horn liegt zerbrochen vor meinem Zelt. Jeden Morgen trete ich einmal drauf. Nur um sicherzugehen.'],
      ['q_barrow_king', 'Die Steppe ist ruhig. Das halte ich nicht lange aus. Grüß Thane von mir, wenn du ihn siehst.'],
    ],
  },
  stablemaster_orla: {
    name: 'Stallmeisterin Orla', idle: 'Ein gutes Tier trägt dich weiter als jedes Schwert.', mounts: true,
    lines: [
      [null, 'Ein gutes Tier trägt dich weiter als jedes Schwert. Aber erst lernst du reiten. Dann reden wir über Preise.'],
      ['q_first_ride', 'Meine Pferde sind nicht billig, weil sie nicht billig sind. Wenn du sparst, gehört dir bald eins. Wenn nicht, gibt es da draußen Bestien, die man zähmen kann. Mit Glück.'],
      ['q_ash_sovereign', 'Man erzählt sich, dass im Thron ein Drache aus Schlacke schläft. Wer den reitet, braucht meine Pferde nicht mehr.'],
    ],
  },
  nomad_kesh: {
    name: 'Kesh, der Nomade', idle: 'Der Wind erzählt, wo die Beute ist. Man muss nur zuhören.',
    lines: [
      [null, 'Der Wind erzählt, wo die Beute ist. Man muss nur zuhören. Und manchmal erzählt er, wo die Hyänen sind.'],
      ['q_steppe_hyenas', 'Meine Ziegen fressen wieder in Ruhe. Das ist in der Steppe mehr wert als Gold.'],
      ['q_barrow_callers', 'Meine Ahnen schlafen wieder. Sie werden dich in ihren Träumen sehen und dir zunicken.'],
    ],
  },
  trader_imra: {
    name: 'Imra, die Händlerin', idle: 'Alles, was du brauchst, für einen Preis, den du nicht magst.',
    lines: [
      [null, 'Alles, was du brauchst, für einen Preis, den du nicht magst. So ist die Steppe.'],
      ['q_steppe_warlord', 'Ohne Khar kommen die Karawanen wieder durch. Heute gibt es bei mir Rabatt. Einen ganz kleinen.'],
      ['q_imra_cargo', 'Seit die Gewürze zurück sind, riecht der ganze Außenposten nach Glutpfeffer. Die Wachen niesen, aber sie beschweren sich nicht.'],
    ],
  },
  warden_thane: {
    name: 'Wächter Thane', idle: 'Bleib auf den Stegen. Das Wasser hier hat Zähne.', bank: true,
    lines: [
      [null, 'Bleib auf den Stegen. Das Wasser hier hat Zähne, und die Zähne haben Hunger.'],
      ['q_marsh_totems', 'Der Nebel ist dünner. Ich sehe jetzt Dinge, die ich lieber nicht sehen würde. Aber besser sehen als gefressen werden.'],
      ['q_bog_horror', 'Seit das Moorgrauen tot ist, schlafen meine Wachen wieder. Schnarchen tun sie auch. Man kann nicht alles haben.'],
      ['q_rot_mother', 'Die Marsch heilt. Langsam, aber sie heilt. Grüß Eskil von mir und sag ihm, dass er mir noch ein Fass schuldet.'],
    ],
  },
  alchemist_brisa: {
    name: 'Alchemistin Brisa', idle: 'Nicht anfassen! Das blubbert, weil es will, nicht weil es fertig ist.',
    lines: [
      [null, 'Nicht anfassen! Das blubbert, weil es will, nicht weil es fertig ist.'],
      ['q_marsh_leeches', 'Die Wächter sind wieder auf den Beinen. Einer hat mir sogar Blumen gebracht. Sumpfblumen. Sie haben mich gebissen.'],
      ['q_marsh_cure', 'Das Heilmittel wirkt! Die Pilze sterben, und die Marsch atmet. Ich bin brillant. Du auch. Etwas.'],
    ],
  },
  trader_moll: {
    name: 'Moll, der Händler', idle: 'Tränke, Verbände, Stiefel ohne Löcher. Was darf es sein?',
    lines: [
      [null, 'Tränke, Verbände, Stiefel ohne Löcher. Was darf es sein? Hier in der Marsch ist alles teuer, besonders das Überleben.'],
      ['q_black_market', 'Die Stege sind sicher, und die Händler kommen zurück. Schlecht für meine Preise, gut für meine Nerven.'],
    ],
  },
  jarl_eskil: {
    name: 'Jarl Eskil', idle: 'Frosthold steht, solange einer von uns noch eine Axt heben kann.', bank: true,
    lines: [
      [null, 'Frosthold steht, solange einer von uns noch eine Axt heben kann. Also für immer.'],
      ['q_frost_beacons', 'Die Leuchtfeuer brennen. Mein Volk schaut wieder nach oben, statt nach unten. Das habe ich dir zu verdanken.'],
      ['q_troll_chief', 'Gorms Hauer hängt über meinem Thron. Ich sehe ihn jeden Morgen an und denke: nicht schlecht, Fremder, nicht schlecht.'],
      ['q_frost_wyrm', 'Der Winter bricht. Zum ersten Mal höre ich Wasser in den Bächen. Geh in die Öde und bring es zu Ende.'],
    ],
  },
  hunter_sigrun: {
    name: 'Jägerin Sigrun', idle: 'Beweg dich leise. Der Schnee verrät jeden Schritt.',
    lines: [
      [null, 'Beweg dich leise. Der Schnee verrät jeden Schritt, und die Pirscher hören alles.'],
      ['q_frozen_knights', 'Die Namen der Ritter stehen jetzt über dem Tor. Deiner steht darunter. Kleiner. Aber er steht da.'],
    ],
  },
  trader_fenn: {
    name: 'Fenn, der Händler', idle: 'Warme Sachen und heiße Tränke. Mehr braucht man hier oben nicht.',
    lines: [
      [null, 'Warme Sachen und heiße Tränke. Mehr braucht man hier oben nicht. Außer Mut. Den verkaufe ich nicht.'],
      ['q_witch_charms', 'Unter den Bäumen friert keiner mehr von innen. Nur noch von außen. Dagegen habe ich Mäntel.'],
    ],
  },
  marshal_corvane: {
    name: 'Marschall Corvane', idle: 'Die Bastion steht. Frag mich nicht, wie lange noch.', bank: true,
    lines: [
      [null, 'Die Bastion steht. Frag mich nicht, wie lange noch. Frag mich lieber, wie viele wir mitnehmen.'],
      ['q_wastes_obelisks', 'Kein Feuerregen mehr. Meine Leute stehen auf den Mauern und schauen einfach nur in den Himmel.'],
      ['q_colossus', 'Der Koloss ist gefallen. Ich habe zehn Jahre auf diesen Tag gewartet. Er war es wert.'],
      ['q_ash_sovereign', 'Es ist vorbei. Wirklich vorbei. Ich weiß nicht, was ich jetzt tun soll. Vielleicht schlafe ich einfach mal.'],
    ],
  },
  pilgrim_aldo: {
    name: 'Pilger Aldo', idle: 'Jeder Schritt zum Thron ist ein Gebet.',
    lines: [
      [null, 'Jeder Schritt zum Thron ist ein Gebet. Leider sind viele meiner Schritte gerade eher Flüche.'],
      ['q_ash_prayers', 'Ich habe am Thron gebetet. Für alle, die nicht angekommen sind. Und für dich, der angekommen ist.'],
    ],
  },
  quartermaster_ryn: {
    name: 'Quartiermeister Ryn', idle: 'Was die Bastion hat, hast du. Gegen Gold natürlich.',
    lines: [
      [null, 'Was die Bastion hat, hast du. Gegen Gold natürlich. Gold hält die Mauern nicht, aber es hält die Leute auf den Mauern.'],
      ['q_serpent_pits', 'Kaltes Wasser in der Glutöde. Wenn du mich fragst, ist das das größere Wunder als der tote Koloss.'],
    ],
  },
};

// Händler ab Stufe 20 (Ausrüstung nur gewöhnlich/ungewöhnlich; Orla verkauft Reittiere, gear: false).
// craft: Schmiede und Verstärken auch unterwegs, damit niemand für die Esse zurück nach Brom oder Dunn muss.
export const VENDORS_40 = {
  trader_imra: { name: 'Imras Karawane', levels: [20, 26], goods: ['superior_potion', 'greater_mana', 'steppe_jerky'], craft: true },
  stablemaster_orla: { name: 'Orlas Stall', gear: false, goods: ['mount_steppe_horse', 'mount_ash_wolf', 'mount_ember_charger'] },
  trader_moll: { name: 'Molls Vorräte', levels: [26, 32], goods: ['superior_potion', 'greater_mana', 'steppe_jerky'], craft: true },
  trader_fenn: { name: 'Fenns Laden', levels: [32, 37], goods: ['supreme_potion', 'supreme_mana', 'steppe_jerky'], craft: true },
  quartermaster_ryn: { name: 'Ryns Vorräte', levels: [37, 40], goods: ['supreme_potion', 'supreme_mana', 'steppe_jerky'], craft: true },
};
