// Zonen- und NPC-Definitionen (werden in world/index.js als Content registriert).
//
// Zonen tragen schon heute die Felder, die ein späterer Server für Kanäle und
// Instanzen braucht: instanced (jede Gruppe bekommt eine eigene Kopie) und
// maxPlayers (Kanal-/Instanzgröße). Lokal gibt es immer genau einen Spieler;
// LocalAuthority.joinZone() liefert eine lokale Instanz.
export const ZONES = {
  emberhollow: {
    name: 'Glutsenke',
    subtitle: 'Startgebiet',
    kind: 'outdoor',
    level: 'emberhollow',
    start: true,
    instanced: false,
    maxPlayers: 40,
    recommendedLevel: '1–3',
    respawnSpawn: 'respawn',
    links: ['catacombs', 'ashwood'],
    enemies: ['wolf', 'wolf_alpha'],
    ambient: [92, 88, 126], // Nacht mit Mondlicht, heller als der Dungeon
  },
  catacombs: {
    name: 'Die Katakomben',
    subtitle: 'Dungeon · Instanz',
    kind: 'dungeon',
    level: 'catacombs',
    instanced: true,
    maxPlayers: 5,
    recommendedLevel: '3–6',
    respawnZone: 'emberhollow',
    respawnSpawn: 'respawn',
    bossId: 'bonelord',
    links: ['emberhollow'],
    enemies: ['skeleton', 'archer', 'spider', 'bonelord'],
    ambient: [46, 38, 66],
  },
  ashwood: {
    name: 'Der Aschenwald',
    subtitle: 'Wildnis',
    kind: 'outdoor',
    level: 'ashwood',
    instanced: false,
    maxPlayers: 40,
    recommendedLevel: '6–11',
    respawnSpawn: 'respawn',
    links: ['emberhollow', 'sunken_temple', 'cinder_peaks'],
    enemies: ['ash_boar', 'bandit', 'bandit_archer', 'thorn_crawler', 'bandit_chief'],
    ambient: [122, 114, 136],
  },
  sunken_temple: {
    name: 'Der Versunkene Tempel',
    subtitle: 'Dungeon · Instanz',
    kind: 'dungeon',
    level: 'sunken_temple',
    instanced: true,
    maxPlayers: 5,
    recommendedLevel: '10–12',
    respawnZone: 'ashwood',
    respawnSpawn: 'from_sunken_temple',
    bossId: 'drowned_priestess',
    links: ['ashwood'],
    enemies: ['drowned', 'tide_cultist', 'temple_guardian', 'drowned_priestess'],
    ambient: [34, 52, 64],
  },
  cinder_peaks: {
    name: 'Die Schlackenhöhen',
    subtitle: 'Wildnis',
    kind: 'outdoor',
    level: 'cinder_peaks',
    instanced: false,
    maxPlayers: 40,
    recommendedLevel: '12–17',
    respawnSpawn: 'respawn',
    links: ['ashwood', 'molten_forge', 'ashen_steppe'],
    enemies: ['fire_imp', 'magma_hound', 'ash_golem', 'cinder_cultist', 'magma_behemoth'],
    ambient: [116, 88, 92],
  },
  molten_forge: {
    name: 'Die Glutschmiede',
    subtitle: 'Dungeon · Instanz',
    kind: 'dungeon',
    level: 'molten_forge',
    instanced: true,
    maxPlayers: 5,
    recommendedLevel: '17–20',
    respawnZone: 'cinder_peaks',
    respawnSpawn: 'from_molten_forge',
    bossId: 'ember_tyrant',
    links: ['cinder_peaks'],
    enemies: ['forge_golem', 'flame_acolyte', 'ember_drake', 'magma_hound', 'forge_warden', 'ember_tyrant'],
    ambient: [58, 36, 40],
  },
  // Endgame (C: progression/trials.js). Betreten nur über die Glutpforte;
  // Nachschub, Boss und Rückkehrportal steuert world/TrialDirector.js.
  ember_trial: {
    name: 'Glutprüfung',
    subtitle: 'Endgame · Instanz',
    kind: 'dungeon',
    level: 'ember_trial',
    instanced: true,
    maxPlayers: 5,
    recommendedLevel: '20',
    trial: true,
    respawnZone: 'emberhollow',
    respawnSpawn: 'from_trial',
    links: ['emberhollow'],
    enemies: [],
    ambient: [100, 72, 74],
  },

  // ---------------------------------------------------------------- Runde 3 (§12.2), Stufe 20–40
  // mountable: Reiten erlaubt (Standard outdoor ja, sonst nein); Flächen mit noMount in der Karte.
  // Wetter, Atmo, Musik: D (Rezepte über die Zonen-ID in gfx/Weather.js).
  ashen_steppe: {
    name: 'Die Aschensteppe',
    subtitle: 'Wildnis',
    kind: 'outdoor',
    level: 'ashen_steppe',
    instanced: false,
    maxPlayers: 40,
    mountable: true,
    recommendedLevel: '20–25',
    respawnSpawn: 'respawn',
    links: ['cinder_peaks', 'howling_barrow', 'blighted_marsh'],
    enemies: ['steppe_raider', 'raider_archer', 'dust_hyena', 'ash_vulture', 'steppe_warlord'],
    ambient: [128, 116, 120],
  },
  howling_barrow: {
    name: 'Das Heulende Hügelgrab',
    subtitle: 'Dungeon · Instanz',
    kind: 'dungeon',
    level: 'howling_barrow',
    instanced: true,
    maxPlayers: 5,
    mountable: false,
    recommendedLevel: '24–26',
    respawnZone: 'ashen_steppe',
    respawnSpawn: 'from_howling_barrow',
    bossId: 'barrow_king',
    links: ['ashen_steppe'],
    enemies: ['barrow_wight', 'grave_hound', 'bone_archer', 'wight_caller', 'barrow_king'],
    ambient: [56, 72, 80],
  },
  blighted_marsh: {
    name: 'Die Faulmarsch',
    subtitle: 'Wildnis',
    kind: 'outdoor',
    level: 'blighted_marsh',
    instanced: false,
    maxPlayers: 40,
    mountable: true,
    recommendedLevel: '25–31',
    respawnSpawn: 'respawn',
    links: ['ashen_steppe', 'spore_hollow', 'frostspire'],
    enemies: ['bog_lurker', 'rot_shaman', 'swamp_leech', 'plague_toad', 'bog_horror'],
    ambient: [100, 118, 104],
  },
  spore_hollow: {
    name: 'Der Sporenschlund',
    subtitle: 'Dungeon · Instanz',
    kind: 'dungeon',
    level: 'spore_hollow',
    instanced: true,
    maxPlayers: 5,
    mountable: false,
    recommendedLevel: '30–32',
    respawnZone: 'blighted_marsh',
    respawnSpawn: 'from_spore_hollow',
    bossId: 'rot_mother',
    links: ['blighted_marsh'],
    enemies: ['sporeling', 'fungal_brute', 'spore_caster', 'rot_mother'],
    ambient: [68, 56, 86],
  },
  frostspire: {
    name: 'Die Frostzinnen',
    subtitle: 'Wildnis',
    kind: 'outdoor',
    level: 'frostspire',
    instanced: false,
    maxPlayers: 40,
    mountable: true,
    recommendedLevel: '31–36',
    respawnSpawn: 'respawn',
    links: ['blighted_marsh', 'rime_caverns', 'ember_wastes'],
    enemies: ['ice_troll', 'frost_wolf', 'rime_witch', 'snow_stalker', 'ice_troll_chief'],
    ambient: [118, 126, 148],
  },
  rime_caverns: {
    name: 'Die Reifhöhlen',
    subtitle: 'Dungeon · Instanz',
    kind: 'dungeon',
    level: 'rime_caverns',
    instanced: true,
    maxPlayers: 5,
    mountable: false,
    recommendedLevel: '35–37',
    respawnZone: 'frostspire',
    respawnSpawn: 'from_rime_caverns',
    bossId: 'frost_wyrm',
    links: ['frostspire'],
    enemies: ['ice_elemental', 'crystal_spider', 'frozen_knight', 'frost_wyrm'],
    ambient: [58, 78, 100],
  },
  ember_wastes: {
    name: 'Die Glutöde',
    subtitle: 'Wildnis',
    kind: 'outdoor',
    level: 'ember_wastes',
    instanced: false,
    maxPlayers: 40,
    mountable: true,
    recommendedLevel: '36–40',
    respawnSpawn: 'respawn',
    links: ['frostspire', 'ashen_throne'],
    enemies: ['ash_wraith', 'cinder_knight', 'magma_serpent', 'ember_cultist_adept', 'waste_colossus'],
    ambient: [124, 90, 84],
  },
  ashen_throne: {
    name: 'Der Aschethron',
    subtitle: 'Dungeon · Instanz',
    kind: 'dungeon',
    level: 'ashen_throne',
    instanced: true,
    maxPlayers: 5,
    mountable: false,
    recommendedLevel: '38–40',
    respawnZone: 'ember_wastes',
    respawnSpawn: 'from_ashen_throne',
    bossId: 'ash_sovereign',
    links: ['ember_wastes'],
    enemies: ['throne_guard', 'ash_priest', 'ember_hellhound', 'throne_sentinel', 'ash_sovereign'],
    ambient: [86, 58, 58],
  },
};

export const NPCS = {
  elder_maren: {
    name: 'Maren',
    title: 'Dorfälteste',
    zoneId: 'emberhollow',
    greeting: 'Die Glut in der Senke wird unruhig, Wanderer.',
    light: { dx: 7, dy: -26, radius: 58, color: [255, 190, 110], sway: true },
    lanternGlow: { dx: 7, dy: 6 },
  },
  smith_brom: {
    name: 'Brom',
    title: 'Schmied',
    zoneId: 'emberhollow',
    greeting: 'Ohne Stahl kommst du da unten nicht weit.',
    fixedFacing: true,
    anvil: { dx: 17, dy: -6 },
  },
  warden_ilsa: {
    name: 'Ilsa',
    title: 'Waldwächterin',
    zoneId: 'ashwood',
    greeting: 'Bleib auf den Wegen. Im Aschenwald jagt alles, was noch atmet.',
  },
  herbalist_oona: {
    name: 'Oona',
    title: 'Kräuterkundige',
    zoneId: 'ashwood',
    greeting: 'Selbst in der Asche wächst noch etwas Heilsames, Kindchen.',
    light: { dx: 6, dy: -12, radius: 50, color: [170, 240, 120] },
  },
  trader_vesk: {
    name: 'Vesk',
    title: 'Händler',
    zoneId: 'ashwood',
    greeting: 'Frische Ware aus drei Tälern! Na ja, zwei. Eins ist abgebrannt.',
  },
  commander_hale: {
    name: 'Hale',
    title: 'Kommandant der Rauhwacht',
    zoneId: 'cinder_peaks',
    greeting: 'Die Feste hält. Noch. Wir brauchen jede Klinge.',
  },
  seer_ysolde: {
    name: 'Ysolde',
    title: 'Seherin',
    zoneId: 'cinder_peaks',
    greeting: 'Ich sehe nicht mit den Augen. Und ich sehe Feuer.',
    light: { dx: 0, dy: -18, radius: 56, color: [190, 140, 255] },
  },
  quartermaster_dunn: {
    name: 'Dunn',
    title: 'Quartiermeister',
    zoneId: 'cinder_peaks',
    greeting: 'Unterschreib hier. Und hier. Dann reden wir über Ausrüstung.',
    fixedFacing: false,
  },

  // ---------------------------------------------------------------- Runde 3 (§12.3), Dialoge/Quests: C
  captain_varra: { name: 'Varra', title: 'Hauptfrau der Steppenwacht', zoneId: 'ashen_steppe', greeting: 'Du kommst von der Feste? Gut. Hier draußen zählt jede Klinge doppelt.' },
  stablemaster_orla: { name: 'Orla', title: 'Stallmeisterin', zoneId: 'ashen_steppe', greeting: 'Ein Reittier sucht sich seinen Reiter aus. Meistens jedenfalls.' },
  nomad_kesh: { name: 'Kesh', title: 'Nomade', zoneId: 'ashen_steppe', greeting: 'Der Wind trägt Asche und Geschichten. Beides brennt in den Augen.' },
  trader_imra: { name: 'Imra', title: 'Händlerin', zoneId: 'ashen_steppe', greeting: 'Was die Steppe nicht frisst, verkaufe ich.' },
  warden_thane: { name: 'Thane', title: 'Moorwächter', zoneId: 'blighted_marsh', greeting: 'Atme flach. Die Sporen sind heute gierig.', light: { dx: 6, dy: -14, radius: 50, color: [180, 230, 140] } },
  alchemist_brisa: { name: 'Brisa', title: 'Alchemistin', zoneId: 'blighted_marsh', greeting: 'Fäulnis ist nur Veränderung mit schlechtem Ruf.', light: { dx: -6, dy: -12, radius: 46, color: [150, 255, 170] } },
  trader_moll: { name: 'Moll', title: 'Händler', zoneId: 'blighted_marsh', greeting: 'Trockene Stiefel? Kosten extra.' },
  jarl_eskil: { name: 'Eskil', title: 'Jarl von Frosthold', zoneId: 'frostspire', greeting: 'Der Winter hier oben verzeiht nichts. Ich auch nicht.' },
  hunter_sigrun: { name: 'Sigrun', title: 'Jägerin', zoneId: 'frostspire', greeting: 'Spuren im Schnee lügen nicht. Trolle schon.' },
  trader_fenn: { name: 'Fenn', title: 'Händler', zoneId: 'frostspire', greeting: 'Pelze, Klingen, heißer Met. Nur das Nötigste.' },
  marshal_corvane: { name: 'Corvane', title: 'Marschall der letzten Bastion', zoneId: 'ember_wastes', greeting: 'Hinter diesen Mauern endet die Welt. Vor ihnen beginnt der Thron.' },
  pilgrim_aldo: { name: 'Aldo', title: 'Pilger', zoneId: 'ember_wastes', greeting: 'Ich suche das Ende der Asche. Bisher fand ich nur mehr Asche.', light: { dx: 5, dy: -16, radius: 44, color: [255, 200, 130] } },
  quartermaster_ryn: { name: 'Ryn', title: 'Quartiermeisterin', zoneId: 'ember_wastes', greeting: 'Jeder Pfeil zählt. Jeder Trank auch. Unterschreib.' },
};
