// Zonen- und NPC-Definitionen (werden in world/index.js als Content registriert).
//
// Zonen tragen schon heute die Felder, die ein späterer Server für Kanäle und
// Instanzen braucht: instanced (jede Gruppe bekommt eine eigene Kopie) und
// maxPlayers (Kanal-/Instanzgröße). Lokal gibt es immer genau einen Spieler;
// LocalAuthority.joinZone() liefert eine lokale Instanz.
export const ZONES = {
  emberhollow: {
    name: 'Glutsenke',
    subtitle: 'Startgebiet',
    kind: 'outdoor',
    level: 'emberhollow',
    start: true,
    instanced: false,
    maxPlayers: 40,
    recommendedLevel: '1–3',
    respawnSpawn: 'respawn',
    links: ['catacombs', 'ashwood'],
    enemies: ['wolf', 'wolf_alpha'],
    ambient: [92, 88, 126], // Nacht mit Mondlicht, heller als der Dungeon
  },
  catacombs: {
    name: 'Die Katakomben',
    subtitle: 'Dungeon · Lokale Instanz',
    kind: 'dungeon',
    level: 'catacombs',
    instanced: true,
    maxPlayers: 5,
    recommendedLevel: '3–6',
    respawnZone: 'emberhollow',
    respawnSpawn: 'respawn',
    bossId: 'bonelord',
    links: ['emberhollow'],
    enemies: ['skeleton', 'archer', 'spider', 'bonelord'],
    ambient: [46, 38, 66],
  },
  ashwood: {
    name: 'Der Aschenwald',
    subtitle: 'Wildnis',
    kind: 'outdoor',
    level: 'ashwood',
    instanced: false,
    maxPlayers: 40,
    recommendedLevel: '6–11',
    respawnSpawn: 'respawn',
    links: ['emberhollow', 'sunken_temple', 'cinder_peaks'],
    enemies: ['ash_boar', 'bandit', 'bandit_archer', 'thorn_crawler', 'bandit_chief'],
    ambient: [100, 94, 118],
  },
  sunken_temple: {
    name: 'Der Versunkene Tempel',
    subtitle: 'Dungeon · Lokale Instanz',
    kind: 'dungeon',
    level: 'sunken_temple',
    instanced: true,
    maxPlayers: 5,
    recommendedLevel: '10–12',
    respawnZone: 'ashwood',
    respawnSpawn: 'from_sunken_temple',
    bossId: 'drowned_priestess',
    links: ['ashwood'],
    enemies: ['drowned', 'tide_cultist', 'temple_guardian', 'drowned_priestess'],
    ambient: [34, 52, 64],
  },
  cinder_peaks: {
    name: 'Die Schlackenhöhen',
    subtitle: 'Wildnis',
    kind: 'outdoor',
    level: 'cinder_peaks',
    instanced: false,
    maxPlayers: 40,
    recommendedLevel: '12–17',
    respawnSpawn: 'respawn',
    links: ['ashwood', 'molten_forge'],
    enemies: ['fire_imp', 'magma_hound', 'ash_golem', 'cinder_cultist', 'magma_behemoth'],
    ambient: [100, 76, 82],
  },
  molten_forge: {
    name: 'Die Glutschmiede',
    subtitle: 'Dungeon · Lokale Instanz',
    kind: 'dungeon',
    level: 'molten_forge',
    instanced: true,
    maxPlayers: 5,
    recommendedLevel: '17–20',
    respawnZone: 'cinder_peaks',
    respawnSpawn: 'from_molten_forge',
    bossId: 'ember_tyrant',
    links: ['cinder_peaks'],
    enemies: ['forge_golem', 'flame_acolyte', 'ember_drake', 'magma_hound', 'forge_warden', 'ember_tyrant'],
    ambient: [58, 36, 40],
  },
  // Endgame (C: progression/trials.js). Betreten nur über die Glutpforte;
  // Nachschub, Boss und Rückkehrportal steuert world/TrialDirector.js.
  ember_trial: {
    name: 'Glutprüfung',
    subtitle: 'Endgame · Lokale Instanz',
    kind: 'dungeon',
    level: 'ember_trial',
    instanced: true,
    maxPlayers: 5,
    recommendedLevel: '20',
    trial: true,
    respawnZone: 'emberhollow',
    respawnSpawn: 'from_trial',
    links: ['emberhollow'],
    enemies: [],
    ambient: [100, 72, 74],
  },
};

export const NPCS = {
  elder_maren: {
    name: 'Maren',
    title: 'Dorfälteste',
    zoneId: 'emberhollow',
    greeting: 'Die Glut in der Senke wird unruhig, Wanderer.',
    light: { dx: 7, dy: -26, radius: 58, color: [255, 190, 110], sway: true },
    lanternGlow: { dx: 7, dy: 6 },
  },
  smith_brom: {
    name: 'Brom',
    title: 'Schmied',
    zoneId: 'emberhollow',
    greeting: 'Ohne Stahl kommst du da unten nicht weit.',
    fixedFacing: true,
    anvil: { dx: 17, dy: -6 },
  },
  warden_ilsa: {
    name: 'Ilsa',
    title: 'Waldwächterin',
    zoneId: 'ashwood',
    greeting: 'Bleib auf den Wegen. Im Aschenwald jagt alles, was noch atmet.',
  },
  herbalist_oona: {
    name: 'Oona',
    title: 'Kräuterkundige',
    zoneId: 'ashwood',
    greeting: 'Selbst in der Asche wächst noch etwas Heilsames, Kindchen.',
    light: { dx: 6, dy: -12, radius: 50, color: [170, 240, 120] },
  },
  trader_vesk: {
    name: 'Vesk',
    title: 'Händler',
    zoneId: 'ashwood',
    greeting: 'Frische Ware aus drei Tälern! Na ja, zwei. Eins ist abgebrannt.',
  },
  commander_hale: {
    name: 'Hale',
    title: 'Kommandant der Rauhwacht',
    zoneId: 'cinder_peaks',
    greeting: 'Die Feste hält. Noch. Wir brauchen jede Klinge.',
  },
  seer_ysolde: {
    name: 'Ysolde',
    title: 'Seherin',
    zoneId: 'cinder_peaks',
    greeting: 'Ich sehe nicht mit den Augen. Und ich sehe Feuer.',
    light: { dx: 0, dy: -18, radius: 56, color: [190, 140, 255] },
  },
  quartermaster_dunn: {
    name: 'Dunn',
    title: 'Quartiermeister',
    zoneId: 'cinder_peaks',
    greeting: 'Unterschreib hier. Und hier. Dann reden wir über Ausrüstung.',
    fixedFacing: false,
  },
};
